package com.ftpix.sss.models;

import java.util.ArrayList;
import java.util.TreeMap;
import java.util.List;
import java.util.Map;


public class CategoryIcons {
    //public static final List<> ALL = new ArrayList<>();
    public static final Map<String, List<String>> ALL = new TreeMap<>();

    static {

        ALL.put("Travel and Map", new ArrayList<>());
        ALL.get("Travel and Map").add("icon-anchor");
        ALL.get("Travel and Map").add("icon-beach");
        ALL.get("Travel and Map").add("icon-big-ben");
        ALL.get("Travel and Map").add("icon-binocular");
        ALL.get("Travel and Map").add("icon-boat-crossing");
        ALL.get("Travel and Map").add("icon-bridge");
        ALL.get("Travel and Map").add("icon-bus");
        ALL.get("Travel and Map").add("icon-camping");
        ALL.get("Travel and Map").add("icon-car");
        ALL.get("Travel and Map").add("icon-caravan");
        ALL.get("Travel and Map").add("icon-center");
        ALL.get("Travel and Map").add("icon-chinese-gate");
        ALL.get("Travel and Map").add("icon-church-2");
        ALL.get("Travel and Map").add("icon-church");
        ALL.get("Travel and Map").add("icon-city");
        ALL.get("Travel and Map").add("icon-compass-2");
        ALL.get("Travel and Map").add("icon-compass-3");
        ALL.get("Travel and Map").add("icon-compass");
        ALL.get("Travel and Map").add("icon-create-route");
        ALL.get("Travel and Map").add("icon-crossing");
        ALL.get("Travel and Map").add("icon-crossroad");
        ALL.get("Travel and Map").add("icon-destination");
        ALL.get("Travel and Map").add("icon-direction-3");
        ALL.get("Travel and Map").add("icon-direction");
        ALL.get("Travel and Map").add("icon-duty-free");
        ALL.get("Travel and Map").add("icon-eco-gas-station");
        ALL.get("Travel and Map").add("icon-eiffel-tower");
        ALL.get("Travel and Map").add("icon-find");
        ALL.get("Travel and Map").add("icon-flag-destination");
        ALL.get("Travel and Map").add("icon-forest");
        ALL.get("Travel and Map").add("icon-freeway");
        ALL.get("Travel and Map").add("icon-gas-station");
        ALL.get("Travel and Map").add("icon-gas");
        ALL.get("Travel and Map").add("icon-gasoline-canister");
        ALL.get("Travel and Map").add("icon-global-search");
        ALL.get("Travel and Map").add("icon-globe");
        ALL.get("Travel and Map").add("icon-gps-add");
        ALL.get("Travel and Map").add("icon-gps-check");
        ALL.get("Travel and Map").add("icon-gps-delete");
        ALL.get("Travel and Map").add("icon-gps-home");
        ALL.get("Travel and Map").add("icon-gps-remove");
        ALL.get("Travel and Map").add("icon-gps-settings");
        ALL.get("Travel and Map").add("icon-gps-signal-off");
        ALL.get("Travel and Map").add("icon-gps-signals");
        ALL.get("Travel and Map").add("icon-gps");
        ALL.get("Travel and Map").add("icon-hikers-bag");
        ALL.get("Travel and Map").add("icon-hotel-2");
        ALL.get("Travel and Map").add("icon-hotel");
        ALL.get("Travel and Map").add("icon-jeep");
        ALL.get("Travel and Map").add("icon-left-turn");
        ALL.get("Travel and Map").add("icon-locate");
        ALL.get("Travel and Map").add("icon-location");
        ALL.get("Travel and Map").add("icon-locations");
        ALL.get("Travel and Map").add("icon-luggage-check");
        ALL.get("Travel and Map").add("icon-luggage");
        ALL.get("Travel and Map").add("icon-map-2");
        ALL.get("Travel and Map").add("icon-map-pin-pointer-2");
        ALL.get("Travel and Map").add("icon-map-pin-pointer-4");
        ALL.get("Travel and Map").add("icon-map-pin-pointer");
        ALL.get("Travel and Map").add("icon-map-pins");
        ALL.get("Travel and Map").add("icon-map");
        ALL.get("Travel and Map").add("icon-monument");
        ALL.get("Travel and Map").add("icon-mountain-map");
        ALL.get("Travel and Map").add("icon-mountains");
        ALL.get("Travel and Map").add("icon-museum");
        ALL.get("Travel and Map").add("icon-passport");
        ALL.get("Travel and Map").add("icon-pin-point-2");
        ALL.get("Travel and Map").add("icon-pisa-tower");
        ALL.get("Travel and Map").add("icon-pyramid");
        ALL.get("Travel and Map").add("icon-radar");
        ALL.get("Travel and Map").add("icon-rails");
        ALL.get("Travel and Map").add("icon-rent-car");
        ALL.get("Travel and Map").add("icon-right-turn");
        ALL.get("Travel and Map").add("icon-road-speed-limit");
        ALL.get("Travel and Map").add("icon-road");
        ALL.get("Travel and Map").add("icon-route-66");
        ALL.get("Travel and Map").add("icon-route");
        ALL.get("Travel and Map").add("icon-sailboat");
        ALL.get("Travel and Map").add("icon-scuba-diving");
        ALL.get("Travel and Map").add("icon-search-destination");
        ALL.get("Travel and Map").add("icon-ship-2");
        ALL.get("Travel and Map").add("icon-ship");
        ALL.get("Travel and Map").add("icon-sonar");
        ALL.get("Travel and Map").add("icon-speed-limit-30");
        ALL.get("Travel and Map").add("icon-speed-limit-60");
        ALL.get("Travel and Map").add("icon-speed-limit-90");
        ALL.get("Travel and Map").add("icon-sunset");
        ALL.get("Travel and Map").add("icon-traffic-lights");
        ALL.get("Travel and Map").add("icon-traffic");
        ALL.get("Travel and Map").add("icon-trailer");
        ALL.get("Travel and Map").add("icon-train");
        ALL.get("Travel and Map").add("icon-tramcar-2");
        ALL.get("Travel and Map").add("icon-tramcar");
        ALL.get("Travel and Map").add("icon-treasure-map");
        ALL.get("Travel and Map").add("icon-truck");
        ALL.get("Travel and Map").add("icon-van-2");
        ALL.get("Travel and Map").add("icon-van");
        ALL.get("Travel and Map").add("icon-world-map");
        ALL.get("Travel and Map").add("icon-world-wide");
        ALL.get("Travel and Map").add("icon-world-wireframe");

        ALL.put("Miscellaneous", new ArrayList<>());
        ALL.get("Miscellaneous").add("icon-baby-carriage");
        ALL.get("Miscellaneous").add("icon-baby-glass");
        ALL.get("Miscellaneous").add("icon-body");
        ALL.get("Miscellaneous").add("icon-cactus");
        ALL.get("Miscellaneous").add("icon-checked");
        ALL.get("Miscellaneous").add("icon-coin-awards");
        ALL.get("Miscellaneous").add("icon-crane");
        ALL.get("Miscellaneous").add("icon-ctrl");
        ALL.get("Miscellaneous").add("icon-drill");
        ALL.get("Miscellaneous").add("icon-drool-towel");
        ALL.get("Miscellaneous").add("icon-dummy");
        ALL.get("Miscellaneous").add("icon-eco-bulb");
        ALL.get("Miscellaneous").add("icon-eco-energy");
        ALL.get("Miscellaneous").add("icon-eco-house");
        ALL.get("Miscellaneous").add("icon-emoticon-angry");
        ALL.get("Miscellaneous").add("icon-emoticon-cool");
        ALL.get("Miscellaneous").add("icon-emoticon-dead");
        ALL.get("Miscellaneous").add("icon-emoticon-geek");
        ALL.get("Miscellaneous").add("icon-emoticon-happy");
        ALL.get("Miscellaneous").add("icon-emoticon-kiss");
        ALL.get("Miscellaneous").add("icon-emoticon-love");
        ALL.get("Miscellaneous").add("icon-emoticon-money");
        ALL.get("Miscellaneous").add("icon-emoticon-mute");
        ALL.get("Miscellaneous").add("icon-emoticon-neutral");
        ALL.get("Miscellaneous").add("icon-emoticon-sad");
        ALL.get("Miscellaneous").add("icon-emoticon-scared");
        ALL.get("Miscellaneous").add("icon-emoticon-smile-2");
        ALL.get("Miscellaneous").add("icon-emoticon-smile");
        ALL.get("Miscellaneous").add("icon-emoticon-smiley");
        ALL.get("Miscellaneous").add("icon-emoticon-straght-face");
        ALL.get("Miscellaneous").add("icon-emoticon-tongue");
        ALL.get("Miscellaneous").add("icon-emoticon-wink");
        ALL.get("Miscellaneous").add("icon-emoticon-wondering");
        ALL.get("Miscellaneous").add("icon-emoticon-worried");
        ALL.get("Miscellaneous").add("icon-factory");
        ALL.get("Miscellaneous").add("icon-fried-eggs");
        ALL.get("Miscellaneous").add("icon-grid");
        ALL.get("Miscellaneous").add("icon-hammer");
        ALL.get("Miscellaneous").add("icon-hand-sprinkler");
        ALL.get("Miscellaneous").add("icon-hand-wash");
        ALL.get("Miscellaneous").add("icon-hastag");
        ALL.get("Miscellaneous").add("icon-lego-face");
        ALL.get("Miscellaneous").add("icon-lego");
        ALL.get("Miscellaneous").add("icon-lifeguard");
        ALL.get("Miscellaneous").add("icon-magnet");
        ALL.get("Miscellaneous").add("icon-pi");
        ALL.get("Miscellaneous").add("icon-pump");
        ALL.get("Miscellaneous").add("icon-recycle-2");
        ALL.get("Miscellaneous").add("icon-recycle");
        ALL.get("Miscellaneous").add("icon-roadblock-2");
        ALL.get("Miscellaneous").add("icon-roadblock");
        ALL.get("Miscellaneous").add("icon-sign");
        ALL.get("Miscellaneous").add("icon-tape-measure");
        ALL.get("Miscellaneous").add("icon-tools");
        ALL.get("Miscellaneous").add("icon-toxic");
        ALL.get("Miscellaneous").add("icon-tumble-dry");
        ALL.get("Miscellaneous").add("icon-wall");
        ALL.get("Miscellaneous").add("icon-wash-2");
        ALL.get("Miscellaneous").add("icon-wash-3");
        ALL.get("Miscellaneous").add("icon-wash");

        ALL.put("Sports", new ArrayList<>());
        ALL.get("Sports").add("icon-air-balloon");
        ALL.get("Sports").add("icon-american-football");
        ALL.get("Sports").add("icon-archery");
        ALL.get("Sports").add("icon-auto-sport");
        ALL.get("Sports").add("icon-badmington-2");
        ALL.get("Sports").add("icon-badmington");
        ALL.get("Sports").add("icon-balance-sheet");
        ALL.get("Sports").add("icon-ballet-shoes");
        ALL.get("Sports").add("icon-barbell");
        ALL.get("Sports").add("icon-baseball-2");
        ALL.get("Sports").add("icon-baseball-hat");
        ALL.get("Sports").add("icon-baseball");
        ALL.get("Sports").add("icon-bell");
        ALL.get("Sports").add("icon-bicycle-2");
        ALL.get("Sports").add("icon-bicycle-chain");
        ALL.get("Sports").add("icon-bicycle");
        ALL.get("Sports").add("icon-billiard-2");
        ALL.get("Sports").add("icon-billiard");
        ALL.get("Sports").add("icon-box-2");
        ALL.get("Sports").add("icon-box-3");
        ALL.get("Sports").add("icon-box-bag-2");
        ALL.get("Sports").add("icon-box-bag-3");
        ALL.get("Sports").add("icon-box-bag");
        ALL.get("Sports").add("icon-box");
        ALL.get("Sports").add("icon-boxing-medal");
        ALL.get("Sports").add("icon-butterfly-catch");
        ALL.get("Sports").add("icon-climber");
        ALL.get("Sports").add("icon-darts");
        ALL.get("Sports").add("icon-diver-foot");
        ALL.get("Sports").add("icon-fishing");
        ALL.get("Sports").add("icon-football");
        ALL.get("Sports").add("icon-golf");
        ALL.get("Sports").add("icon-gymnastics");
        ALL.get("Sports").add("icon-handicap-sport");
        ALL.get("Sports").add("icon-heart-rate-monitor");
        ALL.get("Sports").add("icon-hockey-helmet");
        ALL.get("Sports").add("icon-hockey");
        ALL.get("Sports").add("icon-jersey-2");
        ALL.get("Sports").add("icon-jersey-3");
        ALL.get("Sports").add("icon-jersey");
        ALL.get("Sports").add("icon-kayak");
        ALL.get("Sports").add("icon-kite-flying");
        ALL.get("Sports").add("icon-mesh");
        ALL.get("Sports").add("icon-motor-racing");
        ALL.get("Sports").add("icon-muscle-maker");
        ALL.get("Sports").add("icon-olimpic-fire");
        ALL.get("Sports").add("icon-polo");
        ALL.get("Sports").add("icon-protective-helmets");
        ALL.get("Sports").add("icon-rank");
        ALL.get("Sports").add("icon-roller-skates");
        ALL.get("Sports").add("icon-rope");
        ALL.get("Sports").add("icon-sailing");
        ALL.get("Sports").add("icon-scull");
        ALL.get("Sports").add("icon-skateboard");
        ALL.get("Sports").add("icon-skates");
        ALL.get("Sports").add("icon-ski");
        ALL.get("Sports").add("icon-skydiving");
        ALL.get("Sports").add("icon-sledge");
        ALL.get("Sports").add("icon-snowboard");
        ALL.get("Sports").add("icon-sport-glove");
        ALL.get("Sports").add("icon-surf-2");
        ALL.get("Sports").add("icon-surf");
        ALL.get("Sports").add("icon-sward-play");
        ALL.get("Sports").add("icon-target-2");
        ALL.get("Sports").add("icon-target");
        ALL.get("Sports").add("icon-tennis-2");
        ALL.get("Sports").add("icon-tennis");
        ALL.get("Sports").add("icon-water-bottle");
        ALL.get("Sports").add("icon-water-polo");
        ALL.get("Sports").add("icon-winner");

        ALL.put("Science and Medicine", new ArrayList<>());
        ALL.get("Science and Medicine").add("icon-accident");
        ALL.get("Science and Medicine").add("icon-adhesive-plaster-2");
        ALL.get("Science and Medicine").add("icon-ambulance");
        ALL.get("Science and Medicine").add("icon-blood-2");
        ALL.get("Science and Medicine").add("icon-blood-pressure-monitor");
        ALL.get("Science and Medicine").add("icon-blood-type-2");
        ALL.get("Science and Medicine").add("icon-blood-type");
        ALL.get("Science and Medicine").add("icon-blood");
        ALL.get("Science and Medicine").add("icon-bone");
        ALL.get("Science and Medicine").add("icon-brain-2");
        ALL.get("Science and Medicine").add("icon-brain");
        ALL.get("Science and Medicine").add("icon-breast-cancer");
        ALL.get("Science and Medicine").add("icon-broken-bone");
        ALL.get("Science and Medicine").add("icon-broken-hand");
        ALL.get("Science and Medicine").add("icon-callendar");
        ALL.get("Science and Medicine").add("icon-capsule-2");
        ALL.get("Science and Medicine").add("icon-capsule-3");
        ALL.get("Science and Medicine").add("icon-capsule");
        ALL.get("Science and Medicine").add("icon-condom");
        ALL.get("Science and Medicine").add("icon-contact-lens-2");
        ALL.get("Science and Medicine").add("icon-contact-lens");
        ALL.get("Science and Medicine").add("icon-cream");
        ALL.get("Science and Medicine").add("icon-crutch");
        ALL.get("Science and Medicine").add("icon-dental-floss");
        ALL.get("Science and Medicine").add("icon-dental-implants");
        ALL.get("Science and Medicine").add("icon-dental-tools");
        ALL.get("Science and Medicine").add("icon-dental-x-ray");
        ALL.get("Science and Medicine").add("icon-dentist");
        ALL.get("Science and Medicine").add("icon-digital-balance");
        ALL.get("Science and Medicine").add("icon-doctor");
        ALL.get("Science and Medicine").add("icon-drill2");
        ALL.get("Science and Medicine").add("icon-drop");
        ALL.get("Science and Medicine").add("icon-ekg-2");
        ALL.get("Science and Medicine").add("icon-ekg");
        ALL.get("Science and Medicine").add("icon-eye-exam-2");
        ALL.get("Science and Medicine").add("icon-eye-exam-3");
        ALL.get("Science and Medicine").add("icon-eye-exam-4");
        ALL.get("Science and Medicine").add("icon-eye-exam-5");
        ALL.get("Science and Medicine").add("icon-eye-exam-6");
        ALL.get("Science and Medicine").add("icon-eye-exam");
        ALL.get("Science and Medicine").add("icon-eye");
        ALL.get("Science and Medicine").add("icon-eyedropper");
        ALL.get("Science and Medicine").add("icon-face-mask");
        ALL.get("Science and Medicine").add("icon-first-aid-2");
        ALL.get("Science and Medicine").add("icon-first-aid");
        ALL.get("Science and Medicine").add("icon-foot");
        ALL.get("Science and Medicine").add("icon-gash");
        ALL.get("Science and Medicine").add("icon-gauze");
        ALL.get("Science and Medicine").add("icon-hand-gash-2");
        ALL.get("Science and Medicine").add("icon-hand-gash");
        ALL.get("Science and Medicine").add("icon-hand-grash-3");
        ALL.get("Science and Medicine").add("icon-head-mirror");
        ALL.get("Science and Medicine").add("icon-heart-surgery");
        ALL.get("Science and Medicine").add("icon-helicopter");
        ALL.get("Science and Medicine").add("icon-hollow-tooth");
        ALL.get("Science and Medicine").add("icon-hospital-2");
        ALL.get("Science and Medicine").add("icon-hospital-3");
        ALL.get("Science and Medicine").add("icon-hospital-4");
        ALL.get("Science and Medicine").add("icon-hospital-5");
        ALL.get("Science and Medicine").add("icon-hospital-bed");
        ALL.get("Science and Medicine").add("icon-hospital");
        ALL.get("Science and Medicine").add("icon-infusion");
        ALL.get("Science and Medicine").add("icon-kidney");
        ALL.get("Science and Medicine").add("icon-lungs");
        ALL.get("Science and Medicine").add("icon-medical-document");
        ALL.get("Science and Medicine").add("icon-medicament");
        ALL.get("Science and Medicine").add("icon-medicate");
        ALL.get("Science and Medicine").add("icon-molecule-2");
        ALL.get("Science and Medicine").add("icon-molecule");
        ALL.get("Science and Medicine").add("icon-nurse");
        ALL.get("Science and Medicine").add("icon-pharmacy");
        ALL.get("Science and Medicine").add("icon-pill-2");
        ALL.get("Science and Medicine").add("icon-pill-3");
        ALL.get("Science and Medicine").add("icon-pill-4");
        ALL.get("Science and Medicine").add("icon-pill-5");
        ALL.get("Science and Medicine").add("icon-pill-6");
        ALL.get("Science and Medicine").add("icon-pill-7");
        ALL.get("Science and Medicine").add("icon-pill-box-2");
        ALL.get("Science and Medicine").add("icon-pill-box-3");
        ALL.get("Science and Medicine").add("icon-pill-box-4");
        ALL.get("Science and Medicine").add("icon-pill-box");
        ALL.get("Science and Medicine").add("icon-pill");
        ALL.get("Science and Medicine").add("icon-plant");
        ALL.get("Science and Medicine").add("icon-pulse");
        ALL.get("Science and Medicine").add("icon-radiation");
        ALL.get("Science and Medicine").add("icon-reflex");
        ALL.get("Science and Medicine").add("icon-stetoscope");
        ALL.get("Science and Medicine").add("icon-surgeon-2");
        ALL.get("Science and Medicine").add("icon-surgeon");
        ALL.get("Science and Medicine").add("icon-surgery");
        ALL.get("Science and Medicine").add("icon-tartar");
        ALL.get("Science and Medicine").add("icon-temperature");
        ALL.get("Science and Medicine").add("icon-thermometer");
        ALL.get("Science and Medicine").add("icon-tooth-2");
        ALL.get("Science and Medicine").add("icon-tooth-brush");
        ALL.get("Science and Medicine").add("icon-tooth");
        ALL.get("Science and Medicine").add("icon-trachea");
        ALL.get("Science and Medicine").add("icon-x-ray");

        ALL.put("Gaming", new ArrayList<>());
        ALL.get("Gaming").add("icon-up");
        ALL.get("Gaming").add("icon-ace");
        ALL.get("Gaming").add("icon-aim");
        ALL.get("Gaming").add("icon-alien-invader");
        ALL.get("Gaming").add("icon-arcade");
        ALL.get("Gaming").add("icon-arrows");
        ALL.get("Gaming").add("icon-billiard2");
        ALL.get("Gaming").add("icon-bomb");
        ALL.get("Gaming").add("icon-bowling");
        ALL.get("Gaming").add("icon-bubble-shooter");
        ALL.get("Gaming").add("icon-bulls-eye");
        ALL.get("Gaming").add("icon-castle");
        ALL.get("Gaming").add("icon-cherry");
        ALL.get("Gaming").add("icon-chess-2");
        ALL.get("Gaming").add("icon-chess-3");
        ALL.get("Gaming").add("icon-chess-4");
        ALL.get("Gaming").add("icon-chess");
        ALL.get("Gaming").add("icon-circle-button");
        ALL.get("Gaming").add("icon-clubs");
        ALL.get("Gaming").add("icon-combat-game");
        ALL.get("Gaming").add("icon-console");
        ALL.get("Gaming").add("icon-cristals");
        ALL.get("Gaming").add("icon-crown");
        ALL.get("Gaming").add("icon-cup");
        ALL.get("Gaming").add("icon-darts2");
        ALL.get("Gaming").add("icon-diamonds");
        ALL.get("Gaming").add("icon-dice-2");
        ALL.get("Gaming").add("icon-dice-3");
        ALL.get("Gaming").add("icon-dice-4");
        ALL.get("Gaming").add("icon-dice-5");
        ALL.get("Gaming").add("icon-dice-6");
        ALL.get("Gaming").add("icon-dice");
        ALL.get("Gaming").add("icon-direction2");
        ALL.get("Gaming").add("icon-dominos");
        ALL.get("Gaming").add("icon-favorite-game");
        ALL.get("Gaming").add("icon-game-center");
        ALL.get("Gaming").add("icon-game-console");
        ALL.get("Gaming").add("icon-game-controller");
        ALL.get("Gaming").add("icon-game-stick");
        ALL.get("Gaming").add("icon-gameboy-advanced");
        ALL.get("Gaming").add("icon-gameboy");
        ALL.get("Gaming").add("icon-ghost");
        ALL.get("Gaming").add("icon-hearts");
        ALL.get("Gaming").add("icon-jack");
        ALL.get("Gaming").add("icon-joypad");
        ALL.get("Gaming").add("icon-joystick");
        ALL.get("Gaming").add("icon-king");
        ALL.get("Gaming").add("icon-lime");
        ALL.get("Gaming").add("icon-lucky");
        ALL.get("Gaming").add("icon-maze");
        ALL.get("Gaming").add("icon-motion-controller");
        ALL.get("Gaming").add("icon-nes-cartridge");
        ALL.get("Gaming").add("icon-nes-controller");
        ALL.get("Gaming").add("icon-ninepins");
        ALL.get("Gaming").add("icon-nintendo-ds");
        ALL.get("Gaming").add("icon-pacman");
        ALL.get("Gaming").add("icon-pc-game");
        ALL.get("Gaming").add("icon-pin-pong");
        ALL.get("Gaming").add("icon-pinball");
        ALL.get("Gaming").add("icon-psp");
        ALL.get("Gaming").add("icon-queen");
        ALL.get("Gaming").add("icon-rank2");
        ALL.get("Gaming").add("icon-roulette");
        ALL.get("Gaming").add("icon-slot-game");
        ALL.get("Gaming").add("icon-slots");
        ALL.get("Gaming").add("icon-snes-controller");
        ALL.get("Gaming").add("icon-space-invader");
        ALL.get("Gaming").add("icon-spades");
        ALL.get("Gaming").add("icon-square-button");
        ALL.get("Gaming").add("icon-steering-wheel");
        ALL.get("Gaming").add("icon-sword-2");
        ALL.get("Gaming").add("icon-target2");
        ALL.get("Gaming").add("icon-tetris");
        ALL.get("Gaming").add("icon-triangle-button");
        ALL.get("Gaming").add("icon-weapon");
        ALL.get("Gaming").add("icon-web-cam");
        ALL.get("Gaming").add("icon-wii-controller");
        ALL.get("Gaming").add("icon-wireless-controller");
        ALL.get("Gaming").add("icon-x-button");
        ALL.get("Gaming").add("icon-xo-game");


        ALL.put("Photo and Video", new ArrayList<>());
        ALL.get("Photo and Video").add("icon-d-glass");
        ALL.get("Photo and Video").add("icon-d");
        ALL.get("Photo and Video").add("icon-3-ratio");
        ALL.get("Photo and Video").add("icon-k");
        ALL.get("Photo and Video").add("icon-k2");
        ALL.get("Photo and Video").add("icon-9-ratio");
        ALL.get("Photo and Video").add("icon-480");
        ALL.get("Photo and Video").add("icon-back-counter");
        ALL.get("Photo and Video").add("icon-battery");
        ALL.get("Photo and Video").add("icon-camera-2");
        ALL.get("Photo and Video").add("icon-camera-3");
        ALL.get("Photo and Video").add("icon-camera-4");
        ALL.get("Photo and Video").add("icon-camera-5");
        ALL.get("Photo and Video").add("icon-camera-lens-glass-2");
        ALL.get("Photo and Video").add("icon-camera-lens-glass-3");
        ALL.get("Photo and Video").add("icon-camera-lens-glass-protector");
        ALL.get("Photo and Video").add("icon-camera-lens-glass");
        ALL.get("Photo and Video").add("icon-camera-reel");
        ALL.get("Photo and Video").add("icon-camera-stand");
        ALL.get("Photo and Video").add("icon-camera-upgrade");
        ALL.get("Photo and Video").add("icon-camera");
        ALL.get("Photo and Video").add("icon-contrast");
        ALL.get("Photo and Video").add("icon-director-sign");
        ALL.get("Photo and Video").add("icon-director");
        ALL.get("Photo and Video").add("icon-edit-video");
        ALL.get("Photo and Video").add("icon-film-cd");
        ALL.get("Photo and Video").add("icon-filmstrip");
        ALL.get("Photo and Video").add("icon-filmtape");
        ALL.get("Photo and Video").add("icon-flash-2");
        ALL.get("Photo and Video").add("icon-flash-adjustment");
        ALL.get("Photo and Video").add("icon-flash");
        ALL.get("Photo and Video").add("icon-focus");
        ALL.get("Photo and Video").add("icon-grid2");
        ALL.get("Photo and Video").add("icon-group-photo");
        ALL.get("Photo and Video").add("icon-half-second");
        ALL.get("Photo and Video").add("icon-hd-display");
        ALL.get("Photo and Video").add("icon-hd-film");
        ALL.get("Photo and Video").add("icon-hd");
        ALL.get("Photo and Video").add("icon-hdmi");
        ALL.get("Photo and Video").add("icon-house-video");
        ALL.get("Photo and Video").add("icon-imax");
        ALL.get("Photo and Video").add("icon-landscape-2");
        ALL.get("Photo and Video").add("icon-landscape");
        ALL.get("Photo and Video").add("icon-lentile");
        ALL.get("Photo and Video").add("icon-levels");
        ALL.get("Photo and Video").add("icon-memory-card-2");
        ALL.get("Photo and Video").add("icon-memory-card");
        ALL.get("Photo and Video").add("icon-missing-piece");
        ALL.get("Photo and Video").add("icon-multiple");
        ALL.get("Photo and Video").add("icon-music-cd");
        ALL.get("Photo and Video").add("icon-night-landscape");
        ALL.get("Photo and Video").add("icon-night-portrait");
        ALL.get("Photo and Video").add("icon-no-flash");
        ALL.get("Photo and Video").add("icon-object-glass-protector");
        ALL.get("Photo and Video").add("icon-object-glass");
        ALL.get("Photo and Video").add("icon-one-minute");
        ALL.get("Photo and Video").add("icon-overlay");
        ALL.get("Photo and Video").add("icon-photo-album");
        ALL.get("Photo and Video").add("icon-photo-video");
        ALL.get("Photo and Video").add("icon-play-2");
        ALL.get("Photo and Video").add("icon-play-video");
        ALL.get("Photo and Video").add("icon-play");
        ALL.get("Photo and Video").add("icon-polaroid");
        ALL.get("Photo and Video").add("icon-portrait-2");
        ALL.get("Photo and Video").add("icon-portrait-3");
        ALL.get("Photo and Video").add("icon-portrait");
        ALL.get("Photo and Video").add("icon-projector-2");
        ALL.get("Photo and Video").add("icon-projector");
        ALL.get("Photo and Video").add("icon-random");
        ALL.get("Photo and Video").add("icon-raw");
        ALL.get("Photo and Video").add("icon-recording");
        ALL.get("Photo and Video").add("icon-reflector-2");
        ALL.get("Photo and Video").add("icon-reflector-3");
        ALL.get("Photo and Video").add("icon-reflector");
        ALL.get("Photo and Video").add("icon-sd");
        ALL.get("Photo and Video").add("icon-second-quarter");
        ALL.get("Photo and Video").add("icon-settings");
        ALL.get("Photo and Video").add("icon-shutter");
        ALL.get("Photo and Video").add("icon-timeline");
        ALL.get("Photo and Video").add("icon-timer-2");
        ALL.get("Photo and Video").add("icon-timer");
        ALL.get("Photo and Video").add("icon-tv");
        ALL.get("Photo and Video").add("icon-video-2");
        ALL.get("Photo and Video").add("icon-video-3");
        ALL.get("Photo and Video").add("icon-video-4");
        ALL.get("Photo and Video").add("icon-video-5");
        ALL.get("Photo and Video").add("icon-video-6");
        ALL.get("Photo and Video").add("icon-video-7");
        ALL.get("Photo and Video").add("icon-video-8");
        ALL.get("Photo and Video").add("icon-video-9");
        ALL.get("Photo and Video").add("icon-video-10");
        ALL.get("Photo and Video").add("icon-video-11");
        ALL.get("Photo and Video").add("icon-video-clip");
        ALL.get("Photo and Video").add("icon-video-file");
        ALL.get("Photo and Video").add("icon-video-shutter");
        ALL.get("Photo and Video").add("icon-video");
        ALL.get("Photo and Video").add("icon-videotape");
        ALL.get("Photo and Video").add("icon-vignette");
        ALL.get("Photo and Video").add("icon-voice-file");
        ALL.get("Photo and Video").add("icon-volume");


        ALL.put("Education", new ArrayList<>());
        ALL.get("Education").add("icon-abc");
        ALL.get("Education").add("icon-alarm");
        ALL.get("Education").add("icon-apple-2");
        ALL.get("Education").add("icon-apple");
        ALL.get("Education").add("icon-atom-2");
        ALL.get("Education").add("icon-atom");
        ALL.get("Education").add("icon-beakers");
        ALL.get("Education").add("icon-bell2");
        ALL.get("Education").add("icon-black-board-2");
        ALL.get("Education").add("icon-black-board");
        ALL.get("Education").add("icon-bomb2");
        ALL.get("Education").add("icon-book-2");
        ALL.get("Education").add("icon-book");
        ALL.get("Education").add("icon-briefcase");
        ALL.get("Education").add("icon-building");
        ALL.get("Education").add("icon-bunsen-burner-2");
        ALL.get("Education").add("icon-bunsen-burner");
        ALL.get("Education").add("icon-burn");
        ALL.get("Education").add("icon-calculator");
        ALL.get("Education").add("icon-capsule2");
        ALL.get("Education").add("icon-chair");
        ALL.get("Education").add("icon-coin-avards");
        ALL.get("Education").add("icon-coin-awards-2");
        ALL.get("Education").add("icon-coin-awards-3");
        ALL.get("Education").add("icon-crossing2");
        ALL.get("Education").add("icon-curious");
        ALL.get("Education").add("icon-diploma");
        ALL.get("Education").add("icon-dna");
        ALL.get("Education").add("icon-document-2");
        ALL.get("Education").add("icon-document");
        ALL.get("Education").add("icon-drop-2");
        ALL.get("Education").add("icon-drop2");
        ALL.get("Education").add("icon-einstein-theory");
        ALL.get("Education").add("icon-erlenmeyer-flask-2");
        ALL.get("Education").add("icon-erlenmeyer-flask-3");
        ALL.get("Education").add("icon-erlenmeyer-flask");
        ALL.get("Education").add("icon-experiment-2");
        ALL.get("Education").add("icon-experiment-3");
        ALL.get("Education").add("icon-experiment");
        ALL.get("Education").add("icon-eye-glasses");
        ALL.get("Education").add("icon-fire");
        ALL.get("Education").add("icon-graduation-hat");
        ALL.get("Education").add("icon-graduation");
        ALL.get("Education").add("icon-homework");
        ALL.get("Education").add("icon-idea");
        ALL.get("Education").add("icon-injection");
        ALL.get("Education").add("icon-ink");
        ALL.get("Education").add("icon-laboratory-glasses-2");
        ALL.get("Education").add("icon-laboratory-glasses-3");
        ALL.get("Education").add("icon-laboratory-glasses");
        ALL.get("Education").add("icon-learn-2");
        ALL.get("Education").add("icon-learn-book");
        ALL.get("Education").add("icon-learn");
        ALL.get("Education").add("icon-math-1-01");
        ALL.get("Education").add("icon-math-2");
        ALL.get("Education").add("icon-math-3");
        ALL.get("Education").add("icon-math-4");
        ALL.get("Education").add("icon-math");
        ALL.get("Education").add("icon-microscope-2");
        ALL.get("Education").add("icon-microscope-3");
        ALL.get("Education").add("icon-microscope");
        ALL.get("Education").add("icon-molecule-22");
        ALL.get("Education").add("icon-molecule-3");
        ALL.get("Education").add("icon-molecule2");
        ALL.get("Education").add("icon-mortar-and-pestle");
        ALL.get("Education").add("icon-owl");
        ALL.get("Education").add("icon-paint-2");
        ALL.get("Education").add("icon-paint");
        ALL.get("Education").add("icon-pencils");
        ALL.get("Education").add("icon-periodic-table");
        ALL.get("Education").add("icon-pill-box-22");
        ALL.get("Education").add("icon-pill-box2");
        ALL.get("Education").add("icon-planet");
        ALL.get("Education").add("icon-positive-negative-ion");
        ALL.get("Education").add("icon-question-2");
        ALL.get("Education").add("icon-question");
        ALL.get("Education").add("icon-read-2");
        ALL.get("Education").add("icon-read");
        ALL.get("Education").add("icon-round-botton-flask");
        ALL.get("Education").add("icon-school-alarm");
        ALL.get("Education").add("icon-school-bus");
        ALL.get("Education").add("icon-school-desk");
        ALL.get("Education").add("icon-school");
        ALL.get("Education").add("icon-sport-2");
        ALL.get("Education").add("icon-sport");
        ALL.get("Education").add("icon-stargazer-telescope");
        ALL.get("Education").add("icon-tallboy");
        ALL.get("Education").add("icon-temperature2");
        ALL.get("Education").add("icon-think");
        ALL.get("Education").add("icon-triangle");
        ALL.get("Education").add("icon-university");
        ALL.get("Education").add("icon-vials-2");
        ALL.get("Education").add("icon-vials-3");
        ALL.get("Education").add("icon-vials-4");
        ALL.get("Education").add("icon-vials-5");
        ALL.get("Education").add("icon-vials");
        ALL.get("Education").add("icon-wake-up-alarm");
        ALL.get("Education").add("icon-wash2");
        ALL.get("Education").add("icon-winner-up");
        ALL.get("Education").add("icon-write");


        ALL.put("Beauty and Recreation", new ArrayList<>());
        ALL.get("Beauty and Recreation").add("icon-bamboo");
        ALL.get("Beauty and Recreation").add("icon-bath");
        ALL.get("Beauty and Recreation").add("icon-bathroom-cabinet");
        ALL.get("Beauty and Recreation").add("icon-beauty-case");
        ALL.get("Beauty and Recreation").add("icon-blade");
        ALL.get("Beauty and Recreation").add("icon-blush");
        ALL.get("Beauty and Recreation").add("icon-body-lotion");
        ALL.get("Beauty and Recreation").add("icon-brush-large");
        ALL.get("Beauty and Recreation").add("icon-brush");
        ALL.get("Beauty and Recreation").add("icon-butterfly");
        ALL.get("Beauty and Recreation").add("icon-candle");
        ALL.get("Beauty and Recreation").add("icon-comb");
        ALL.get("Beauty and Recreation").add("icon-duble-eye-pencil");
        ALL.get("Beauty and Recreation").add("icon-epilator");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows-1");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows-2");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows-3");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows-4");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows-5");
        ALL.get("Beauty and Recreation").add("icon-eye-shadows");
        ALL.get("Beauty and Recreation").add("icon-eye2");
        ALL.get("Beauty and Recreation").add("icon-eyelash-curlers");
        ALL.get("Beauty and Recreation").add("icon-face-cream-2");
        ALL.get("Beauty and Recreation").add("icon-face-cream");
        ALL.get("Beauty and Recreation").add("icon-female");
        ALL.get("Beauty and Recreation").add("icon-flower");
        ALL.get("Beauty and Recreation").add("icon-foot-file");
        ALL.get("Beauty and Recreation").add("icon-hair-dryer");
        ALL.get("Beauty and Recreation").add("icon-hair-scissor");
        ALL.get("Beauty and Recreation").add("icon-hairbrush");
        ALL.get("Beauty and Recreation").add("icon-hairs");
        ALL.get("Beauty and Recreation").add("icon-heart");
        ALL.get("Beauty and Recreation").add("icon-leaf");
        ALL.get("Beauty and Recreation").add("icon-lip");
        ALL.get("Beauty and Recreation").add("icon-lipstick");
        ALL.get("Beauty and Recreation").add("icon-liquid-soap");
        ALL.get("Beauty and Recreation").add("icon-lotion");
        ALL.get("Beauty and Recreation").add("icon-manicure");
        ALL.get("Beauty and Recreation").add("icon-mascara");
        ALL.get("Beauty and Recreation").add("icon-mask");
        ALL.get("Beauty and Recreation").add("icon-mirror-2");
        ALL.get("Beauty and Recreation").add("icon-mirror-3");
        ALL.get("Beauty and Recreation").add("icon-mirror");
        ALL.get("Beauty and Recreation").add("icon-nail-polish");
        ALL.get("Beauty and Recreation").add("icon-nail-scissor");
        ALL.get("Beauty and Recreation").add("icon-nail");
        ALL.get("Beauty and Recreation").add("icon-oil");
        ALL.get("Beauty and Recreation").add("icon-parfume");
        ALL.get("Beauty and Recreation").add("icon-razors");
        ALL.get("Beauty and Recreation").add("icon-sauna");
        ALL.get("Beauty and Recreation").add("icon-scissor");
        ALL.get("Beauty and Recreation").add("icon-shaver");
        ALL.get("Beauty and Recreation").add("icon-shaving-foam");
        ALL.get("Beauty and Recreation").add("icon-shower-gel");
        ALL.get("Beauty and Recreation").add("icon-spray");
        ALL.get("Beauty and Recreation").add("icon-toothbrush");
        ALL.get("Beauty and Recreation").add("icon-towel-2");
        ALL.get("Beauty and Recreation").add("icon-towel");
        ALL.get("Beauty and Recreation").add("icon-washbasin-2");
        ALL.get("Beauty and Recreation").add("icon-washbasin");


        ALL.put("Shopping and Mall", new ArrayList<>());
        ALL.get("Shopping and Mall").add("icon-h-service");
        ALL.get("Shopping and Mall").add("icon-atm");
        ALL.get("Shopping and Mall").add("icon-badge");
        ALL.get("Shopping and Mall").add("icon-bag-2");
        ALL.get("Shopping and Mall").add("icon-bag");
        ALL.get("Shopping and Mall").add("icon-bank");
        ALL.get("Shopping and Mall").add("icon-barcode");
        ALL.get("Shopping and Mall").add("icon-belt");
        ALL.get("Shopping and Mall").add("icon-birhtday-gift");
        ALL.get("Shopping and Mall").add("icon-bitcoin");
        ALL.get("Shopping and Mall").add("icon-bow");
        ALL.get("Shopping and Mall").add("icon-calculate");
        ALL.get("Shopping and Mall").add("icon-calculator-2");
        ALL.get("Shopping and Mall").add("icon-card-pay");
        ALL.get("Shopping and Mall").add("icon-card");
        ALL.get("Shopping and Mall").add("icon-cash-register");
        ALL.get("Shopping and Mall").add("icon-cents");
        ALL.get("Shopping and Mall").add("icon-change-money");
        ALL.get("Shopping and Mall").add("icon-check-payment");
        ALL.get("Shopping and Mall").add("icon-closed");
        ALL.get("Shopping and Mall").add("icon-closet");
        ALL.get("Shopping and Mall").add("icon-coin");
        ALL.get("Shopping and Mall").add("icon-couch");
        ALL.get("Shopping and Mall").add("icon-delivery");
        ALL.get("Shopping and Mall").add("icon-discount");
        ALL.get("Shopping and Mall").add("icon-dollar");
        ALL.get("Shopping and Mall").add("icon-dress");
        ALL.get("Shopping and Mall").add("icon-euro");
        ALL.get("Shopping and Mall").add("icon-exchange");
        ALL.get("Shopping and Mall").add("icon-exit-2");
        ALL.get("Shopping and Mall").add("icon-exit");
        ALL.get("Shopping and Mall").add("icon-fresh");
        ALL.get("Shopping and Mall").add("icon-gold");
        ALL.get("Shopping and Mall").add("icon-jewelry");
        ALL.get("Shopping and Mall").add("icon-lamp");
        ALL.get("Shopping and Mall").add("icon-lingerie");
        ALL.get("Shopping and Mall").add("icon-lock-card");
        ALL.get("Shopping and Mall").add("icon-market");
        ALL.get("Shopping and Mall").add("icon-money-2");
        ALL.get("Shopping and Mall").add("icon-money-bag");
        ALL.get("Shopping and Mall").add("icon-new");
        ALL.get("Shopping and Mall").add("icon-non-stop");
        ALL.get("Shopping and Mall").add("icon-online-shopping-2");
        ALL.get("Shopping and Mall").add("icon-online-shopping-3");
        ALL.get("Shopping and Mall").add("icon-online-shopping");
        ALL.get("Shopping and Mall").add("icon-open");
        ALL.get("Shopping and Mall").add("icon-package-delivery-2");
        ALL.get("Shopping and Mall").add("icon-package-delivery");
        ALL.get("Shopping and Mall").add("icon-package");
        ALL.get("Shopping and Mall").add("icon-pants");
        ALL.get("Shopping and Mall").add("icon-pay-card-2");
        ALL.get("Shopping and Mall").add("icon-pay-card-3");
        ALL.get("Shopping and Mall").add("icon-paypass");
        ALL.get("Shopping and Mall").add("icon-pound");
        ALL.get("Shopping and Mall").add("icon-promotion");
        ALL.get("Shopping and Mall").add("icon-protected");
        ALL.get("Shopping and Mall").add("icon-qr-code");
        ALL.get("Shopping and Mall").add("icon-receipt");
        ALL.get("Shopping and Mall").add("icon-safe-deposit");
        ALL.get("Shopping and Mall").add("icon-sale-2");
        ALL.get("Shopping and Mall").add("icon-sale-3");
        ALL.get("Shopping and Mall").add("icon-sale");
        ALL.get("Shopping and Mall").add("icon-savings");
        ALL.get("Shopping and Mall").add("icon-sealed-box");
        ALL.get("Shopping and Mall").add("icon-search-box");
        ALL.get("Shopping and Mall").add("icon-security-camera");
        ALL.get("Shopping and Mall").add("icon-security");
        ALL.get("Shopping and Mall").add("icon-serch-barcode");
        ALL.get("Shopping and Mall").add("icon-shirt");
        ALL.get("Shopping and Mall").add("icon-shopping-bag-2");
        ALL.get("Shopping and Mall").add("icon-shopping-bag");
        ALL.get("Shopping and Mall").add("icon-shopping-briefcase");
        ALL.get("Shopping and Mall").add("icon-shopping-cart-add");
        ALL.get("Shopping and Mall").add("icon-shopping-cart-download");
        ALL.get("Shopping and Mall").add("icon-shopping-cart-full");
        ALL.get("Shopping and Mall").add("icon-shopping-cart-remove");
        ALL.get("Shopping and Mall").add("icon-shopping-cart-upload");
        ALL.get("Shopping and Mall").add("icon-shopping-cart");
        ALL.get("Shopping and Mall").add("icon-shopping-list");
        ALL.get("Shopping and Mall").add("icon-sold");
        ALL.get("Shopping and Mall").add("icon-t-shirt");
        ALL.get("Shopping and Mall").add("icon-tag");
        ALL.get("Shopping and Mall").add("icon-verified-payment");
        ALL.get("Shopping and Mall").add("icon-voucher-2");
        ALL.get("Shopping and Mall").add("icon-voucher-3");
        ALL.get("Shopping and Mall").add("icon-voucher");
        ALL.get("Shopping and Mall").add("icon-wallet-2");
        ALL.get("Shopping and Mall").add("icon-wallet");
        ALL.get("Shopping and Mall").add("icon-wireless-access");
        ALL.get("Shopping and Mall").add("icon-yen");


        ALL.put("Office", new ArrayList<>());
        ALL.get("Office").add("icon-badge2");
        ALL.get("Office").add("icon-balance-sheet2");
        ALL.get("Office").add("icon-board");
        ALL.get("Office").add("icon-books");
        ALL.get("Office").add("icon-boss");
        ALL.get("Office").add("icon-briefcase2");
        ALL.get("Office").add("icon-business-center-2");
        ALL.get("Office").add("icon-business-center-3");
        ALL.get("Office").add("icon-business-center");
        ALL.get("Office").add("icon-business-man");
        ALL.get("Office").add("icon-business-woman");
        ALL.get("Office").add("icon-cactus2");
        ALL.get("Office").add("icon-calculator2");
        ALL.get("Office").add("icon-calendar-add");
        ALL.get("Office").add("icon-calendar-remove");
        ALL.get("Office").add("icon-calendar");
        ALL.get("Office").add("icon-chess2");
        ALL.get("Office").add("icon-clips");
        ALL.get("Office").add("icon-decreases");
        ALL.get("Office").add("icon-desk-lamp");
        ALL.get("Office").add("icon-diamond");
        ALL.get("Office").add("icon-diary-2");
        ALL.get("Office").add("icon-diary-3");
        ALL.get("Office").add("icon-diary");
        ALL.get("Office").add("icon-diploma2");
        ALL.get("Office").add("icon-documents-2");
        ALL.get("Office").add("icon-documents-holder-2");
        ALL.get("Office").add("icon-documents-holder-3");
        ALL.get("Office").add("icon-documents-holder");
        ALL.get("Office").add("icon-documents");
        ALL.get("Office").add("icon-dollar-change");
        ALL.get("Office").add("icon-dollar2");
        ALL.get("Office").add("icon-duct-tape-2");
        ALL.get("Office").add("icon-duct-tape");
        ALL.get("Office").add("icon-dustbin");
        ALL.get("Office").add("icon-envelope");
        ALL.get("Office").add("icon-eye-glass");
        ALL.get("Office").add("icon-fan");
        ALL.get("Office").add("icon-fax");
        ALL.get("Office").add("icon-file-holder");
        ALL.get("Office").add("icon-flag");
        ALL.get("Office").add("icon-flower2");
        ALL.get("Office").add("icon-folder-2");
        ALL.get("Office").add("icon-folder");
        ALL.get("Office").add("icon-globe2");
        ALL.get("Office").add("icon-growyh");
        ALL.get("Office").add("icon-inbox");
        ALL.get("Office").add("icon-internation-target");
        ALL.get("Office").add("icon-international-download");
        ALL.get("Office").add("icon-international");
        ALL.get("Office").add("icon-key");
        ALL.get("Office").add("icon-lamp2");
        ALL.get("Office").add("icon-letter");
        ALL.get("Office").add("icon-loundspeaker");
        ALL.get("Office").add("icon-mail-outbox");
        ALL.get("Office").add("icon-mail-read");
        ALL.get("Office").add("icon-mail-sent");
        ALL.get("Office").add("icon-mail-sync");
        ALL.get("Office").add("icon-mails-outbox");
        ALL.get("Office").add("icon-money-22");
        ALL.get("Office").add("icon-money");
        ALL.get("Office").add("icon-note");
        ALL.get("Office").add("icon-office-chair");
        ALL.get("Office").add("icon-office-desk-2");
        ALL.get("Office").add("icon-office-desk");
        ALL.get("Office").add("icon-office-tallboy");
        ALL.get("Office").add("icon-outbox");
        ALL.get("Office").add("icon-paper-plane");
        ALL.get("Office").add("icon-paper-shredders");
        ALL.get("Office").add("icon-perforator");
        ALL.get("Office").add("icon-phone-book");
        ALL.get("Office").add("icon-print");
        ALL.get("Office").add("icon-projector2");
        ALL.get("Office").add("icon-protection");
        ALL.get("Office").add("icon-puzzle");
        ALL.get("Office").add("icon-ruler");
        ALL.get("Office").add("icon-sand-glass");
        ALL.get("Office").add("icon-sharpener");
        ALL.get("Office").add("icon-sign-post");
        ALL.get("Office").add("icon-stamp-2");
        ALL.get("Office").add("icon-stamp");
        ALL.get("Office").add("icon-stapler-2");
        ALL.get("Office").add("icon-stapler-remover");
        ALL.get("Office").add("icon-stapler");
        ALL.get("Office").add("icon-statistics-2");
        ALL.get("Office").add("icon-statistics-3");
        ALL.get("Office").add("icon-statistics-4");
        ALL.get("Office").add("icon-statistics-5");
        ALL.get("Office").add("icon-statistics-6");
        ALL.get("Office").add("icon-statistics-7");
        ALL.get("Office").add("icon-statistics");
        ALL.get("Office").add("icon-target3");
        ALL.get("Office").add("icon-task");
        ALL.get("Office").add("icon-time");
        ALL.get("Office").add("icon-trade");
        ALL.get("Office").add("icon-triangle-ruler");
        ALL.get("Office").add("icon-typewriter");
        ALL.get("Office").add("icon-zip-lock-file");


        ALL.put("Holidays and Celebration", new ArrayList<>());
        ALL.get("Holidays and Celebration").add("icon-angel");
        ALL.get("Holidays and Celebration").add("icon-badge3");
        ALL.get("Holidays and Celebration").add("icon-balloon-figures");
        ALL.get("Holidays and Celebration").add("icon-balloons");
        ALL.get("Holidays and Celebration").add("icon-barrel");
        ALL.get("Holidays and Celebration").add("icon-bat");
        ALL.get("Holidays and Celebration").add("icon-bell3");
        ALL.get("Holidays and Celebration").add("icon-bible");
        ALL.get("Holidays and Celebration").add("icon-birthsday-cake");
        ALL.get("Holidays and Celebration").add("icon-birthsday-candle");
        ALL.get("Holidays and Celebration").add("icon-bloody-hatchet");
        ALL.get("Holidays and Celebration").add("icon-bouquet-2");
        ALL.get("Holidays and Celebration").add("icon-bouquet");
        ALL.get("Holidays and Celebration").add("icon-bow2");
        ALL.get("Holidays and Celebration").add("icon-broken-egg");
        ALL.get("Holidays and Celebration").add("icon-broken-heart");
        ALL.get("Holidays and Celebration").add("icon-broom");
        ALL.get("Holidays and Celebration").add("icon-butterfly2");
        ALL.get("Holidays and Celebration").add("icon-cake");
        ALL.get("Holidays and Celebration").add("icon-candle-2");
        ALL.get("Holidays and Celebration").add("icon-candle-3");
        ALL.get("Holidays and Celebration").add("icon-candle2");
        ALL.get("Holidays and Celebration").add("icon-candy");
        ALL.get("Holidays and Celebration").add("icon-catkin");
        ALL.get("Holidays and Celebration").add("icon-cauldron");
        ALL.get("Holidays and Celebration").add("icon-cemetery-2");
        ALL.get("Holidays and Celebration").add("icon-cemetery-3");
        ALL.get("Holidays and Celebration").add("icon-cemetery");
        ALL.get("Holidays and Celebration").add("icon-champagne");
        ALL.get("Holidays and Celebration").add("icon-christmas-tree");
        ALL.get("Holidays and Celebration").add("icon-church2");
        ALL.get("Holidays and Celebration").add("icon-coffin");
        ALL.get("Holidays and Celebration").add("icon-confetti");
        ALL.get("Holidays and Celebration").add("icon-crown2");
        ALL.get("Holidays and Celebration").add("icon-cupido-arrow");
        ALL.get("Holidays and Celebration").add("icon-cylinder");
        ALL.get("Holidays and Celebration").add("icon-deer");
        ALL.get("Holidays and Celebration").add("icon-devil");
        ALL.get("Holidays and Celebration").add("icon-disco-globe");
        ALL.get("Holidays and Celebration").add("icon-door-ornament");
        ALL.get("Holidays and Celebration").add("icon-easter-basket");
        ALL.get("Holidays and Celebration").add("icon-easter-bunny");
        ALL.get("Holidays and Celebration").add("icon-easter-egg-2");
        ALL.get("Holidays and Celebration").add("icon-easter-egg-3");
        ALL.get("Holidays and Celebration").add("icon-easter-egg");
        ALL.get("Holidays and Celebration").add("icon-easter");
        ALL.get("Holidays and Celebration").add("icon-elixir");
        ALL.get("Holidays and Celebration").add("icon-eye3");
        ALL.get("Holidays and Celebration").add("icon-fireplace");
        ALL.get("Holidays and Celebration").add("icon-firework-2");
        ALL.get("Holidays and Celebration").add("icon-firework");
        ALL.get("Holidays and Celebration").add("icon-flag2");
        ALL.get("Holidays and Celebration").add("icon-ghost2");
        ALL.get("Holidays and Celebration").add("icon-gift-2");
        ALL.get("Holidays and Celebration").add("icon-gift");
        ALL.get("Holidays and Celebration").add("icon-gingerbread");
        ALL.get("Holidays and Celebration").add("icon-globe3");
        ALL.get("Holidays and Celebration").add("icon-halloween-pumpkin");
        ALL.get("Holidays and Celebration").add("icon-hat");
        ALL.get("Holidays and Celebration").add("icon-heart-flag");
        ALL.get("Holidays and Celebration").add("icon-hearts2");
        ALL.get("Holidays and Celebration").add("icon-karaoke");
        ALL.get("Holidays and Celebration").add("icon-lamb");
        ALL.get("Holidays and Celebration").add("icon-light");
        ALL.get("Holidays and Celebration").add("icon-love-2");
        ALL.get("Holidays and Celebration").add("icon-love-3");
        ALL.get("Holidays and Celebration").add("icon-love-4");
        ALL.get("Holidays and Celebration").add("icon-love-key");
        ALL.get("Holidays and Celebration").add("icon-love-letter-2");
        ALL.get("Holidays and Celebration").add("icon-love-letter");
        ALL.get("Holidays and Celebration").add("icon-love-message");
        ALL.get("Holidays and Celebration").add("icon-love");
        ALL.get("Holidays and Celebration").add("icon-magician");
        ALL.get("Holidays and Celebration").add("icon-mistletoe");
        ALL.get("Holidays and Celebration").add("icon-owl2");
        ALL.get("Holidays and Celebration").add("icon-party-decoration-2");
        ALL.get("Holidays and Celebration").add("icon-party-decoration");
        ALL.get("Holidays and Celebration").add("icon-party-mask");
        ALL.get("Holidays and Celebration").add("icon-party-whistle");
        ALL.get("Holidays and Celebration").add("icon-pine");
        ALL.get("Holidays and Celebration").add("icon-reaper");
        ALL.get("Holidays and Celebration").add("icon-santa-boots");
        ALL.get("Holidays and Celebration").add("icon-secret-love");
        ALL.get("Holidays and Celebration").add("icon-shamrock");
        ALL.get("Holidays and Celebration").add("icon-sign2");
        ALL.get("Holidays and Celebration").add("icon-sledge2");
        ALL.get("Holidays and Celebration").add("icon-slice-cake");
        ALL.get("Holidays and Celebration").add("icon-snow-globe");
        ALL.get("Holidays and Celebration").add("icon-snowflake-2");
        ALL.get("Holidays and Celebration").add("icon-snowflake");
        ALL.get("Holidays and Celebration").add("icon-snowman");
        ALL.get("Holidays and Celebration").add("icon-sock");
        ALL.get("Holidays and Celebration").add("icon-soda");
        ALL.get("Holidays and Celebration").add("icon-star-ornament");
        ALL.get("Holidays and Celebration").add("icon-star");
        ALL.get("Holidays and Celebration").add("icon-treasure");
        ALL.get("Holidays and Celebration").add("icon-valentines-day");
        ALL.get("Holidays and Celebration").add("icon-weekend-house");
        ALL.get("Holidays and Celebration").add("icon-wishlist");
        ALL.get("Holidays and Celebration").add("icon-witch-hat");


        ALL.put("Weather", new ArrayList<>());
        ALL.get("Weather").add("icon-attention");
        ALL.get("Weather").add("icon-celsius");
        ALL.get("Weather").add("icon-changing-weather");
        ALL.get("Weather").add("icon-cirro-stratus-2");
        ALL.get("Weather").add("icon-cirro-stratus");
        ALL.get("Weather").add("icon-clody-night-4");
        ALL.get("Weather").add("icon-cloud-2");
        ALL.get("Weather").add("icon-cloud");
        ALL.get("Weather").add("icon-cloudy-2");
        ALL.get("Weather").add("icon-cloudy-day-2");
        ALL.get("Weather").add("icon-cloudy-day");
        ALL.get("Weather").add("icon-cloudy-fullmoon");
        ALL.get("Weather").add("icon-cloudy-night-2");
        ALL.get("Weather").add("icon-cloudy-night-3");
        ALL.get("Weather").add("icon-cloudy-night");
        ALL.get("Weather").add("icon-cloudy");
        ALL.get("Weather").add("icon-cold-1");
        ALL.get("Weather").add("icon-cold-2");
        ALL.get("Weather").add("icon-cold");
        ALL.get("Weather").add("icon-daily-cirro-stratus");
        ALL.get("Weather").add("icon-day-thunderstorm");
        ALL.get("Weather").add("icon-est");
        ALL.get("Weather").add("icon-fahrenheit");
        ALL.get("Weather").add("icon-first-quarter-moon");
        ALL.get("Weather").add("icon-fog");
        ALL.get("Weather").add("icon-freezing-rain-2");
        ALL.get("Weather").add("icon-freezing-rain");
        ALL.get("Weather").add("icon-full-moon");
        ALL.get("Weather").add("icon-hail-2");
        ALL.get("Weather").add("icon-hail");
        ALL.get("Weather").add("icon-half-moon");
        ALL.get("Weather").add("icon-hot-2");
        ALL.get("Weather").add("icon-hot");
        ALL.get("Weather").add("icon-ice-crystals");
        ALL.get("Weather").add("icon-ice");
        ALL.get("Weather").add("icon-last-quarter-moon");
        ALL.get("Weather").add("icon-lightning");
        ALL.get("Weather").add("icon-moon");
        ALL.get("Weather").add("icon-na-weather");
        ALL.get("Weather").add("icon-night-2");
        ALL.get("Weather").add("icon-night-thunderstorm");
        ALL.get("Weather").add("icon-night");
        ALL.get("Weather").add("icon-nightly-cirro-stratus");
        ALL.get("Weather").add("icon-nord");
        ALL.get("Weather").add("icon-precipitation-2");
        ALL.get("Weather").add("icon-precipitation-3");
        ALL.get("Weather").add("icon-precipitation");
        ALL.get("Weather").add("icon-rain-2");
        ALL.get("Weather").add("icon-rain-3");
        ALL.get("Weather").add("icon-rain");
        ALL.get("Weather").add("icon-rainbow-2");
        ALL.get("Weather").add("icon-rainbow");
        ALL.get("Weather").add("icon-rainfall-2");
        ALL.get("Weather").add("icon-rainfall");
        ALL.get("Weather").add("icon-rainy-day-2");
        ALL.get("Weather").add("icon-rainy-day");
        ALL.get("Weather").add("icon-rainy-fullmoon");
        ALL.get("Weather").add("icon-rainy-night-2");
        ALL.get("Weather").add("icon-rainy-night");
        ALL.get("Weather").add("icon-snow-flake");
        ALL.get("Weather").add("icon-snow");
        ALL.get("Weather").add("icon-solar-eclipse");
        ALL.get("Weather").add("icon-south");
        ALL.get("Weather").add("icon-star-sky");
        ALL.get("Weather").add("icon-storm-2");
        ALL.get("Weather").add("icon-storm-sunrise");
        ALL.get("Weather").add("icon-storm");
        ALL.get("Weather").add("icon-summer");
        ALL.get("Weather").add("icon-sun-2");
        ALL.get("Weather").add("icon-sun");
        ALL.get("Weather").add("icon-sunny-day");
        ALL.get("Weather").add("icon-sunny-rainbow");
        ALL.get("Weather").add("icon-sunny-winter-day");
        ALL.get("Weather").add("icon-sunrise-2");
        ALL.get("Weather").add("icon-sunrise");
        ALL.get("Weather").add("icon-sunset2");
        ALL.get("Weather").add("icon-thermomether");
        ALL.get("Weather").add("icon-thunder");
        ALL.get("Weather").add("icon-thunderstorm-2");
        ALL.get("Weather").add("icon-thunderstorm-3");
        ALL.get("Weather").add("icon-thunderstorm");
        ALL.get("Weather").add("icon-tornado-2");
        ALL.get("Weather").add("icon-tornado");
        ALL.get("Weather").add("icon-umbrella");
        ALL.get("Weather").add("icon-uv-rays");
        ALL.get("Weather").add("icon-water-lavel");
        ALL.get("Weather").add("icon-water-wave");
        ALL.get("Weather").add("icon-weathercock");
        ALL.get("Weather").add("icon-west");
        ALL.get("Weather").add("icon-wind-2");
        ALL.get("Weather").add("icon-wind-3");
        ALL.get("Weather").add("icon-wind-4");
        ALL.get("Weather").add("icon-wind");
        ALL.get("Weather").add("icon-windmill");
        ALL.get("Weather").add("icon-windy-rainy-day-2");
        ALL.get("Weather").add("icon-windy-rainy-day");
        ALL.get("Weather").add("icon-windy-summer-day");
        ALL.get("Weather").add("icon-windy-winter-day");
        ALL.get("Weather").add("icon-winter-night");
        ALL.get("Weather").add("icon-winter");


        ALL.put("Tabs and Social", new ArrayList<>());
        ALL.get("Tabs and Social").add("icon-amazon");
        ALL.get("Tabs and Social").add("icon-android");
        ALL.get("Tabs and Social").add("icon-apple2");
        ALL.get("Tabs and Social").add("icon-behance");
        ALL.get("Tabs and Social").add("icon-blogger");
        ALL.get("Tabs and Social").add("icon-bootstrap");
        ALL.get("Tabs and Social").add("icon-chrome");
        ALL.get("Tabs and Social").add("icon-css");
        ALL.get("Tabs and Social").add("icon-delicious");
        ALL.get("Tabs and Social").add("icon-deviantart");
        ALL.get("Tabs and Social").add("icon-digg");
        ALL.get("Tabs and Social").add("icon-dribbble");
        ALL.get("Tabs and Social").add("icon-dropbox");
        ALL.get("Tabs and Social").add("icon-drupal");
        ALL.get("Tabs and Social").add("icon-envato");
        ALL.get("Tabs and Social").add("icon-evernote");
        ALL.get("Tabs and Social").add("icon-explorer");
        ALL.get("Tabs and Social").add("icon-facebook");
        ALL.get("Tabs and Social").add("icon-flickr");
        ALL.get("Tabs and Social").add("icon-github");
        ALL.get("Tabs and Social").add("icon-google-drive");
        ALL.get("Tabs and Social").add("icon-google-play");
        ALL.get("Tabs and Social").add("icon-google-plus");
        ALL.get("Tabs and Social").add("icon-grooveshark");
        ALL.get("Tabs and Social").add("icon-html");
        ALL.get("Tabs and Social").add("icon-instagram");
        ALL.get("Tabs and Social").add("icon-kickstarter");
        ALL.get("Tabs and Social").add("icon-linked-in");
        ALL.get("Tabs and Social").add("icon-medium");
        ALL.get("Tabs and Social").add("icon-monitor-tablet-horizontal");
        ALL.get("Tabs and Social").add("icon-monitor");
        ALL.get("Tabs and Social").add("icon-myspace");
        ALL.get("Tabs and Social").add("icon-opera");
        ALL.get("Tabs and Social").add("icon-paypal");
        ALL.get("Tabs and Social").add("icon-phone");
        ALL.get("Tabs and Social").add("icon-picasa");
        ALL.get("Tabs and Social").add("icon-pinterest");
        ALL.get("Tabs and Social").add("icon-reddit");
        ALL.get("Tabs and Social").add("icon-rss");
        ALL.get("Tabs and Social").add("icon-skype");
        ALL.get("Tabs and Social").add("icon-soundcloud");
        ALL.get("Tabs and Social").add("icon-spotify");
        ALL.get("Tabs and Social").add("icon-stumbleupon");
        ALL.get("Tabs and Social").add("icon-tablet-vertical-layout");
        ALL.get("Tabs and Social").add("icon-tablet");
        ALL.get("Tabs and Social").add("icon-tumblr");
        ALL.get("Tabs and Social").add("icon-twitter");
        ALL.get("Tabs and Social").add("icon-ubuntu");
        ALL.get("Tabs and Social").add("icon-vimeo");
        ALL.get("Tabs and Social").add("icon-vine");
        ALL.get("Tabs and Social").add("icon-wikipedia");
        ALL.get("Tabs and Social").add("icon-window-tab");
        ALL.get("Tabs and Social").add("icon-windows");
        ALL.get("Tabs and Social").add("icon-xbox");
        ALL.get("Tabs and Social").add("icon-yahoo");
        ALL.get("Tabs and Social").add("icon-youtube");


        ALL.put("Media", new ArrayList<>());
        ALL.get("Media").add("icon-alert");
        ALL.get("Media").add("icon-antenna");
        ALL.get("Media").add("icon-bluetooth");
        ALL.get("Media").add("icon-bulb");
        ALL.get("Media").add("icon-camera2");
        ALL.get("Media").add("icon-chart");
        ALL.get("Media").add("icon-cloud2");
        ALL.get("Media").add("icon-cursor");
        ALL.get("Media").add("icon-dash");
        ALL.get("Media").add("icon-dashboard");
        ALL.get("Media").add("icon-dislike");
        ALL.get("Media").add("icon-electricity");
        ALL.get("Media").add("icon-equilizer");
        ALL.get("Media").add("icon-firewire");
        ALL.get("Media").add("icon-flag3");
        ALL.get("Media").add("icon-floppy");
        ALL.get("Media").add("icon-frames");
        ALL.get("Media").add("icon-gear");
        ALL.get("Media").add("icon-gears");
        ALL.get("Media").add("icon-headphones");
        ALL.get("Media").add("icon-invisible");
        ALL.get("Media").add("icon-keyboard");
        ALL.get("Media").add("icon-like");
        ALL.get("Media").add("icon-media-storage");
        ALL.get("Media").add("icon-melody");
        ALL.get("Media").add("icon-microphone");
        ALL.get("Media").add("icon-monitor2");
        ALL.get("Media").add("icon-mouse");
        ALL.get("Media").add("icon-music");
        ALL.get("Media").add("icon-mute");
        ALL.get("Media").add("icon-network");
        ALL.get("Media").add("icon-next");
        ALL.get("Media").add("icon-notebook");
        ALL.get("Media").add("icon-off");
        ALL.get("Media").add("icon-on");
        ALL.get("Media").add("icon-pause");
        ALL.get("Media").add("icon-phone-incoming");
        ALL.get("Media").add("icon-phone-outgoing");
        ALL.get("Media").add("icon-phone2");
        ALL.get("Media").add("icon-photo-classic");
        ALL.get("Media").add("icon-photo");
        ALL.get("Media").add("icon-photography");
        ALL.get("Media").add("icon-photos");
        ALL.get("Media").add("icon-play-video2");
        ALL.get("Media").add("icon-power");
        ALL.get("Media").add("icon-printer-2");
        ALL.get("Media").add("icon-refresh");
        ALL.get("Media").add("icon-repair");
        ALL.get("Media").add("icon-replay");
        ALL.get("Media").add("icon-search");
        ALL.get("Media").add("icon-settings-bar");
        ALL.get("Media").add("icon-shuffle");
        ALL.get("Media").add("icon-signal-1");
        ALL.get("Media").add("icon-statistics2");
        ALL.get("Media").add("icon-sync");
        ALL.get("Media").add("icon-tablet2");
        ALL.get("Media").add("icon-time2");
        ALL.get("Media").add("icon-timer2");
        ALL.get("Media").add("icon-tv2");
        ALL.get("Media").add("icon-up-left");
        ALL.get("Media").add("icon-up-right");
        ALL.get("Media").add("icon-up2");
        ALL.get("Media").add("icon-usb");
        ALL.get("Media").add("icon-video2");
        ALL.get("Media").add("icon-volume2");
        ALL.get("Media").add("icon-wifi-1");


        ALL.put("Clothes", new ArrayList<>());
        ALL.get("Clothes").add("icon-baseball-cap");
        ALL.get("Clothes").add("icon-bath-cloak");
        ALL.get("Clothes").add("icon-belt2");
        ALL.get("Clothes").add("icon-blouse-2");
        ALL.get("Clothes").add("icon-blouse-3");
        ALL.get("Clothes").add("icon-blouse-4");
        ALL.get("Clothes").add("icon-blouse-5");
        ALL.get("Clothes").add("icon-blouse-pants");
        ALL.get("Clothes").add("icon-blouse");
        ALL.get("Clothes").add("icon-boots");
        ALL.get("Clothes").add("icon-bow-tie");
        ALL.get("Clothes").add("icon-brief");
        ALL.get("Clothes").add("icon-briefcase3");
        ALL.get("Clothes").add("icon-button-2");
        ALL.get("Clothes").add("icon-button");
        ALL.get("Clothes").add("icon-capri-pants");
        ALL.get("Clothes").add("icon-chain");
        ALL.get("Clothes").add("icon-clothes-hanging-2");
        ALL.get("Clothes").add("icon-clothes-hanging-4");
        ALL.get("Clothes").add("icon-clothes-hanging-5");
        ALL.get("Clothes").add("icon-clothes-hanging");
        ALL.get("Clothes").add("icon-coat-2");
        ALL.get("Clothes").add("icon-coat");
        ALL.get("Clothes").add("icon-cufflinks");
        ALL.get("Clothes").add("icon-cutter");
        ALL.get("Clothes").add("icon-cutting-pattern");
        ALL.get("Clothes").add("icon-dirty-t-shirt");
        ALL.get("Clothes").add("icon-dress-2");
        ALL.get("Clothes").add("icon-dress-3");
        ALL.get("Clothes").add("icon-dress-4");
        ALL.get("Clothes").add("icon-dress-5");
        ALL.get("Clothes").add("icon-dress-6");
        ALL.get("Clothes").add("icon-dress-7");
        ALL.get("Clothes").add("icon-dress-8");
        ALL.get("Clothes").add("icon-dress-9");
        ALL.get("Clothes").add("icon-dress2");
        ALL.get("Clothes").add("icon-dryer");
        ALL.get("Clothes").add("icon-earrings-2");
        ALL.get("Clothes").add("icon-earrings-3");
        ALL.get("Clothes").add("icon-earrings");
        ALL.get("Clothes").add("icon-fabric");
        ALL.get("Clothes").add("icon-gloves-2");
        ALL.get("Clothes").add("icon-gloves");
        ALL.get("Clothes").add("icon-hand-bag");
        ALL.get("Clothes").add("icon-heart-chain");
        ALL.get("Clothes").add("icon-ironing-board");
        ALL.get("Clothes").add("icon-jeans");
        ALL.get("Clothes").add("icon-leather");
        ALL.get("Clothes").add("icon-lingerie-set");
        ALL.get("Clothes").add("icon-mannequin-2");
        ALL.get("Clothes").add("icon-mannequin");
        ALL.get("Clothes").add("icon-maternity-brief");
        ALL.get("Clothes").add("icon-measure");
        ALL.get("Clothes").add("icon-mirror2");
        ALL.get("Clothes").add("icon-necktie");
        ALL.get("Clothes").add("icon-neckties-hanging");
        ALL.get("Clothes").add("icon-needle-set");
        ALL.get("Clothes").add("icon-needlework");
        ALL.get("Clothes").add("icon-pants2");
        ALL.get("Clothes").add("icon-pick-buttonhole-cutter");
        ALL.get("Clothes").add("icon-pijamas");
        ALL.get("Clothes").add("icon-pincusion");
        ALL.get("Clothes").add("icon-pins");
        ALL.get("Clothes").add("icon-ring");
        ALL.get("Clothes").add("icon-safety-pin");
        ALL.get("Clothes").add("icon-scissor2");
        ALL.get("Clothes").add("icon-sewing-machine");
        ALL.get("Clothes").add("icon-sewing");
        ALL.get("Clothes").add("icon-shears");
        ALL.get("Clothes").add("icon-shirt-1");
        ALL.get("Clothes").add("icon-shirt-2");
        ALL.get("Clothes").add("icon-shirt-3");
        ALL.get("Clothes").add("icon-shirt2");
        ALL.get("Clothes").add("icon-shoe");
        ALL.get("Clothes").add("icon-skein");
        ALL.get("Clothes").add("icon-skirt-2");
        ALL.get("Clothes").add("icon-skirt-3");
        ALL.get("Clothes").add("icon-skirt");
        ALL.get("Clothes").add("icon-slipper");
        ALL.get("Clothes").add("icon-socks");
        ALL.get("Clothes").add("icon-suit-2");
        ALL.get("Clothes").add("icon-suit-3");
        ALL.get("Clothes").add("icon-suit");
        ALL.get("Clothes").add("icon-summer-hat");
        ALL.get("Clothes").add("icon-swimsuit-2");
        ALL.get("Clothes").add("icon-swimsuit-3");
        ALL.get("Clothes").add("icon-swimsuit-4");
        ALL.get("Clothes").add("icon-swimsuit");
        ALL.get("Clothes").add("icon-t-shirt-2");
        ALL.get("Clothes").add("icon-t-shirt2");
        ALL.get("Clothes").add("icon-textile-sample");
        ALL.get("Clothes").add("icon-textile");
        ALL.get("Clothes").add("icon-thimble");
        ALL.get("Clothes").add("icon-thread-2");
        ALL.get("Clothes").add("icon-thread");
        ALL.get("Clothes").add("icon-tie");
        ALL.get("Clothes").add("icon-top-hat");
        ALL.get("Clothes").add("icon-travel-bag");
        ALL.get("Clothes").add("icon-trousers");
        ALL.get("Clothes").add("icon-umbrella2");
        ALL.get("Clothes").add("icon-vest-2");
        ALL.get("Clothes").add("icon-vest");
        ALL.get("Clothes").add("icon-wallet2");
        ALL.get("Clothes").add("icon-watch");
        ALL.get("Clothes").add("icon-winter-hats");
        ALL.get("Clothes").add("icon-yarn");
        ALL.get("Clothes").add("icon-zip");


        ALL.put("Hotel", new ArrayList<>());
        ALL.get("Hotel").add("icon-airplane");
        ALL.get("Hotel").add("icon-alarm2");
        ALL.get("Hotel").add("icon-barbell2");
        ALL.get("Hotel").add("icon-bathtube");
        ALL.get("Hotel").add("icon-beach2");
        ALL.get("Hotel").add("icon-bed");
        ALL.get("Hotel").add("icon-bell4");
        ALL.get("Hotel").add("icon-billiards");
        ALL.get("Hotel").add("icon-breakfast");
        ALL.get("Hotel").add("icon-bunk-bead");
        ALL.get("Hotel").add("icon-bus2");
        ALL.get("Hotel").add("icon-car2");
        ALL.get("Hotel").add("icon-card2");
        ALL.get("Hotel").add("icon-cash");
        ALL.get("Hotel").add("icon-champagne2");
        ALL.get("Hotel").add("icon-charger");
        ALL.get("Hotel").add("icon-cleaning");
        ALL.get("Hotel").add("icon-cocktails");
        ALL.get("Hotel").add("icon-cold2");
        ALL.get("Hotel").add("icon-cutlery");
        ALL.get("Hotel").add("icon-disabled");
        ALL.get("Hotel").add("icon-dish");
        ALL.get("Hotel").add("icon-double-bed");
        ALL.get("Hotel").add("icon-double-room");
        ALL.get("Hotel").add("icon-dvd");
        ALL.get("Hotel").add("icon-elevator");
        ALL.get("Hotel").add("icon-escalator");
        ALL.get("Hotel").add("icon-fan2");
        ALL.get("Hotel").add("icon-fire-extinguisher");
        ALL.get("Hotel").add("icon-fishing2");
        ALL.get("Hotel").add("icon-five-person");
        ALL.get("Hotel").add("icon-five-star");
        ALL.get("Hotel").add("icon-foot-ball");
        ALL.get("Hotel").add("icon-four-person");
        ALL.get("Hotel").add("icon-four-star");
        ALL.get("Hotel").add("icon-fridge");
        ALL.get("Hotel").add("icon-game");
        ALL.get("Hotel").add("icon-gift2");
        ALL.get("Hotel").add("icon-golf2");
        ALL.get("Hotel").add("icon-hair-dryer2");
        ALL.get("Hotel").add("icon-hairdresser");
        ALL.get("Hotel").add("icon-hand-bag2");
        ALL.get("Hotel").add("icon-hanger");
        ALL.get("Hotel").add("icon-hanging-towel");
        ALL.get("Hotel").add("icon-hospital2");
        ALL.get("Hotel").add("icon-hot-food");
        ALL.get("Hotel").add("icon-hotel-22");
        ALL.get("Hotel").add("icon-hotel2");
        ALL.get("Hotel").add("icon-house-keeper");
        ALL.get("Hotel").add("icon-ice-cream");
        ALL.get("Hotel").add("icon-information");
        ALL.get("Hotel").add("icon-iron");
        ALL.get("Hotel").add("icon-key2");
        ALL.get("Hotel").add("icon-lamp3");
        ALL.get("Hotel").add("icon-leaf2");
        ALL.get("Hotel").add("icon-man");
        ALL.get("Hotel").add("icon-massage");
        ALL.get("Hotel").add("icon-music2");
        ALL.get("Hotel").add("icon-no-pet");
        ALL.get("Hotel").add("icon-no-smoking");
        ALL.get("Hotel").add("icon-non-stop-2");
        ALL.get("Hotel").add("icon-non-stop-3");
        ALL.get("Hotel").add("icon-non-stop-4");
        ALL.get("Hotel").add("icon-non-stop2");
        ALL.get("Hotel").add("icon-not-disturb");
        ALL.get("Hotel").add("icon-one-star");
        ALL.get("Hotel").add("icon-package-delivery2");
        ALL.get("Hotel").add("icon-palm");
        ALL.get("Hotel").add("icon-parking");
        ALL.get("Hotel").add("icon-pc");
        ALL.get("Hotel").add("icon-pet");
        ALL.get("Hotel").add("icon-phone3");
        ALL.get("Hotel").add("icon-photo2");
        ALL.get("Hotel").add("icon-pin");
        ALL.get("Hotel").add("icon-poker");
        ALL.get("Hotel").add("icon-police");
        ALL.get("Hotel").add("icon-recycle2");
        ALL.get("Hotel").add("icon-roasted-chicken");
        ALL.get("Hotel").add("icon-room-card");
        ALL.get("Hotel").add("icon-room-key");
        ALL.get("Hotel").add("icon-room-service");
        ALL.get("Hotel").add("icon-safe-bag");
        ALL.get("Hotel").add("icon-safe");
        ALL.get("Hotel").add("icon-scissors");
        ALL.get("Hotel").add("icon-service");
        ALL.get("Hotel").add("icon-serving-food-3");
        ALL.get("Hotel").add("icon-serving-food");
        ALL.get("Hotel").add("icon-ship2");
        ALL.get("Hotel").add("icon-shopping");
        ALL.get("Hotel").add("icon-shower");
        ALL.get("Hotel").add("icon-signpost");
        ALL.get("Hotel").add("icon-single-bed-2");
        ALL.get("Hotel").add("icon-single-bed");
        ALL.get("Hotel").add("icon-single-room");
        ALL.get("Hotel").add("icon-six-person");
        ALL.get("Hotel").add("icon-smoking");
        ALL.get("Hotel").add("icon-stairs");
        ALL.get("Hotel").add("icon-stove");
        ALL.get("Hotel").add("icon-swim");
        ALL.get("Hotel").add("icon-swimming-pool");
        ALL.get("Hotel").add("icon-tap");
        ALL.get("Hotel").add("icon-taxi");
        ALL.get("Hotel").add("icon-temperature3");
        ALL.get("Hotel").add("icon-tennis2");
        ALL.get("Hotel").add("icon-three-person");
        ALL.get("Hotel").add("icon-three-star");
        ALL.get("Hotel").add("icon-ticket");
        ALL.get("Hotel").add("icon-toilet-paper");
        ALL.get("Hotel").add("icon-toilet");
        ALL.get("Hotel").add("icon-treadmill");
        ALL.get("Hotel").add("icon-tv3");
        ALL.get("Hotel").add("icon-two-star");
        ALL.get("Hotel").add("icon-umbrella3");
        ALL.get("Hotel").add("icon-valet");
        ALL.get("Hotel").add("icon-vip");
        ALL.get("Hotel").add("icon-washing-machine");
        ALL.get("Hotel").add("icon-wi-fi");
        ALL.get("Hotel").add("icon-wine");
        ALL.get("Hotel").add("icon-wireless");
        ALL.get("Hotel").add("icon-woman");


        ALL.put("Food", new ArrayList<>());
        ALL.get("Food").add("icon-apple3");
        ALL.get("Food").add("icon-artichokes");
        ALL.get("Food").add("icon-avocado");
        ALL.get("Food").add("icon-bacon");
        ALL.get("Food").add("icon-bakery");
        ALL.get("Food").add("icon-banana");
        ALL.get("Food").add("icon-beater");
        ALL.get("Food").add("icon-beer");
        ALL.get("Food").add("icon-beetroot");
        ALL.get("Food").add("icon-biscuit");
        ALL.get("Food").add("icon-boiled-egg");
        ALL.get("Food").add("icon-boottle");
        ALL.get("Food").add("icon-bottle-opener");
        ALL.get("Food").add("icon-bread");
        ALL.get("Food").add("icon-broccoli");
        ALL.get("Food").add("icon-burrito");
        ALL.get("Food").add("icon-cake-slice");
        ALL.get("Food").add("icon-cake2");
        ALL.get("Food").add("icon-candy2");
        ALL.get("Food").add("icon-canned-fish");
        ALL.get("Food").add("icon-carrot");
        ALL.get("Food").add("icon-cayenne-pepper");
        ALL.get("Food").add("icon-cereal");
        ALL.get("Food").add("icon-champagne-cup");
        ALL.get("Food").add("icon-champagne3");
        ALL.get("Food").add("icon-cheese");
        ALL.get("Food").add("icon-chef");
        ALL.get("Food").add("icon-cherry2");
        ALL.get("Food").add("icon-chinese-food-01");
        ALL.get("Food").add("icon-chinese-food-2");
        ALL.get("Food").add("icon-chocolate");
        ALL.get("Food").add("icon-cocktail");
        ALL.get("Food").add("icon-coconut");
        ALL.get("Food").add("icon-coffee-boottle");
        ALL.get("Food").add("icon-coffee-maker");
        ALL.get("Food").add("icon-coffee");
        ALL.get("Food").add("icon-cooking");
        ALL.get("Food").add("icon-corn");
        ALL.get("Food").add("icon-croissante");
        ALL.get("Food").add("icon-cutlery-2");
        ALL.get("Food").add("icon-cutlery2");
        ALL.get("Food").add("icon-cutting-board-2");
        ALL.get("Food").add("icon-cutting-board");
        ALL.get("Food").add("icon-donuts");
        ALL.get("Food").add("icon-drink-menu");
        ALL.get("Food").add("icon-filter");
        ALL.get("Food").add("icon-fish");
        ALL.get("Food").add("icon-food-menu");
        ALL.get("Food").add("icon-frankfurter");
        ALL.get("Food").add("icon-french-fries");
        ALL.get("Food").add("icon-fried-egg");
        ALL.get("Food").add("icon-grape");
        ALL.get("Food").add("icon-grill-cutlery");
        ALL.get("Food").add("icon-ham");
        ALL.get("Food").add("icon-hamburger");
        ALL.get("Food").add("icon-hand-beater");
        ALL.get("Food").add("icon-holding-2");
        ALL.get("Food").add("icon-holding");
        ALL.get("Food").add("icon-honey");
        ALL.get("Food").add("icon-hot-dog");
        ALL.get("Food").add("icon-hot-soup");
        ALL.get("Food").add("icon-hot-tea");
        ALL.get("Food").add("icon-ice-cream-2");
        ALL.get("Food").add("icon-ice-cream2");
        ALL.get("Food").add("icon-jelly");
        ALL.get("Food").add("icon-kitchen-balance");
        ALL.get("Food").add("icon-knife");
        ALL.get("Food").add("icon-limonade");
        ALL.get("Food").add("icon-lobster");
        ALL.get("Food").add("icon-lollipop-2");
        ALL.get("Food").add("icon-lollipop");
        ALL.get("Food").add("icon-melon");
        ALL.get("Food").add("icon-milk");
        ALL.get("Food").add("icon-muffin");
        ALL.get("Food").add("icon-mushroom");
        ALL.get("Food").add("icon-olive-oil");
        ALL.get("Food").add("icon-olive");
        ALL.get("Food").add("icon-onion");
        ALL.get("Food").add("icon-orange");
        ALL.get("Food").add("icon-pan-2");
        ALL.get("Food").add("icon-pan");
        ALL.get("Food").add("icon-pear");
        ALL.get("Food").add("icon-peas");
        ALL.get("Food").add("icon-pepper");
        ALL.get("Food").add("icon-pizza-slice");
        ALL.get("Food").add("icon-pizza");
        ALL.get("Food").add("icon-plates-cutlery");
        ALL.get("Food").add("icon-popcorn");
        ALL.get("Food").add("icon-pot-2");
        ALL.get("Food").add("icon-pot");
        ALL.get("Food").add("icon-pretzel");
        ALL.get("Food").add("icon-rasp-2");
        ALL.get("Food").add("icon-rasp");
        ALL.get("Food").add("icon-roast-chicken");
        ALL.get("Food").add("icon-salami");
        ALL.get("Food").add("icon-salt-pepper");
        ALL.get("Food").add("icon-sandwich");
        ALL.get("Food").add("icon-sausage");
        ALL.get("Food").add("icon-seed");
        ALL.get("Food").add("icon-serving-food-2");
        ALL.get("Food").add("icon-serving-food2");
        ALL.get("Food").add("icon-skewers");
        ALL.get("Food").add("icon-soda2");
        ALL.get("Food").add("icon-souce");
        ALL.get("Food").add("icon-soup-spoon");
        ALL.get("Food").add("icon-spaghetti");
        ALL.get("Food").add("icon-steak");
        ALL.get("Food").add("icon-strawberries");
        ALL.get("Food").add("icon-sushi");
        ALL.get("Food").add("icon-tako");
        ALL.get("Food").add("icon-tea-maker");
        ALL.get("Food").add("icon-toaster");
        ALL.get("Food").add("icon-toilet2");
        ALL.get("Food").add("icon-tortilla-chips");
        ALL.get("Food").add("icon-utensil-2");
        ALL.get("Food").add("icon-utensil");
        ALL.get("Food").add("icon-wine-cups");
        ALL.get("Food").add("icon-wine-opener");
        ALL.get("Food").add("icon-wine2");


        ALL.put("Audio", new ArrayList<>());
        ALL.get("Audio").add("icon-accordion");
        ALL.get("Audio").add("icon-amplifier");
        ALL.get("Audio").add("icon-audio-cables");
        ALL.get("Audio").add("icon-banjo");
        ALL.get("Audio").add("icon-bougarabou");
        ALL.get("Audio").add("icon-cable-2");
        ALL.get("Audio").add("icon-cable");
        ALL.get("Audio").add("icon-cassette-player-2");
        ALL.get("Audio").add("icon-cassette-player");
        ALL.get("Audio").add("icon-cassette");
        ALL.get("Audio").add("icon-cd-case");
        ALL.get("Audio").add("icon-cd-music");
        ALL.get("Audio").add("icon-cd-writer-2");
        ALL.get("Audio").add("icon-cd-writer");
        ALL.get("Audio").add("icon-cd");
        ALL.get("Audio").add("icon-contrabass-trombone");
        ALL.get("Audio").add("icon-cornet");
        ALL.get("Audio").add("icon-cymbal");
        ALL.get("Audio").add("icon-drum-2");
        ALL.get("Audio").add("icon-drum-3");
        ALL.get("Audio").add("icon-drum-cymbal");
        ALL.get("Audio").add("icon-drum");
        ALL.get("Audio").add("icon-earphones-2");
        ALL.get("Audio").add("icon-earphones-3");
        ALL.get("Audio").add("icon-earphones-4");
        ALL.get("Audio").add("icon-earphones");
        ALL.get("Audio").add("icon-electric-guitar-2");
        ALL.get("Audio").add("icon-electric-guitar");
        ALL.get("Audio").add("icon-flute");
        ALL.get("Audio").add("icon-gramophone");
        ALL.get("Audio").add("icon-guitar-2");
        ALL.get("Audio").add("icon-guitar");
        ALL.get("Audio").add("icon-harp");
        ALL.get("Audio").add("icon-headset");
        ALL.get("Audio").add("icon-keytar");
        ALL.get("Audio").add("icon-maraca");
        ALL.get("Audio").add("icon-megaphone");
        ALL.get("Audio").add("icon-metronome");
        ALL.get("Audio").add("icon-microphone2");
        ALL.get("Audio").add("icon-mp3-player");
        ALL.get("Audio").add("icon-mp4-player-2");
        ALL.get("Audio").add("icon-mp4-player-3");
        ALL.get("Audio").add("icon-mp4-player");
        ALL.get("Audio").add("icon-music-box");
        ALL.get("Audio").add("icon-music-button");
        ALL.get("Audio").add("icon-music-computer");
        ALL.get("Audio").add("icon-music-download");
        ALL.get("Audio").add("icon-music-folder-2");
        ALL.get("Audio").add("icon-music-folder");
        ALL.get("Audio").add("icon-music3");
        ALL.get("Audio").add("icon-organ");
        ALL.get("Audio").add("icon-panflute");
        ALL.get("Audio").add("icon-piano-key");
        ALL.get("Audio").add("icon-piano");
        ALL.get("Audio").add("icon-record");
        ALL.get("Audio").add("icon-saxophone");
        ALL.get("Audio").add("icon-soprillo-saxophone");
        ALL.get("Audio").add("icon-sound-wave-2");
        ALL.get("Audio").add("icon-sound-wave");
        ALL.get("Audio").add("icon-speaker-2");
        ALL.get("Audio").add("icon-speaker-3");
        ALL.get("Audio").add("icon-speaker");
        ALL.get("Audio").add("icon-tambourine");
        ALL.get("Audio").add("icon-triangle2");
        ALL.get("Audio").add("icon-trumpet");
        ALL.get("Audio").add("icon-tuning-fork");
        ALL.get("Audio").add("icon-turntable");
        ALL.get("Audio").add("icon-vinyl-records");
        ALL.get("Audio").add("icon-violin");
        ALL.get("Audio").add("icon-voice-recorder-2");
        ALL.get("Audio").add("icon-voice-recorder-3");
        ALL.get("Audio").add("icon-voice-recorder");
        ALL.get("Audio").add("icon-volume-2");
        ALL.get("Audio").add("icon-volume-3");
        ALL.get("Audio").add("icon-volume-4");
        ALL.get("Audio").add("icon-volume-boost-2");
        ALL.get("Audio").add("icon-volume-boost");
        ALL.get("Audio").add("icon-volume3");
        ALL.get("Audio").add("icon-wirelessmicrophone");
        ALL.get("Audio").add("icon-wireless-headset");
        ALL.get("Audio").add("icon-xilofon");

    }
}
