FROM amazoncorretto:21

RUN mkdir /app && mkdir /config && mkdir /app-files


COPY ./target/SpendSpentSpent-*.jar  /app/SpendSpentSpent.jar

ADD ./docker/run.sh /run.sh

EXPOSE 9001

VOLUME "/config"
VOLUME "/app-files"

RUN chmod +x /run.sh

CMD "./run.sh"
