FROM openjdk:17

RUN mkdir /app && mkdir /config


COPY ./target/SpendSpentSpent-*.jar  /app/SpendSpentSpent.jar

ADD ./docker/run.sh /run.sh

EXPOSE 9001

VOLUME "/config"

RUN chmod +x /run.sh

CMD "./run.sh"
