/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables;


import com.ftpix.sss.dsl.Keys;
import com.ftpix.sss.dsl.PUBLIC;
import com.ftpix.sss.dsl.tables.Expense.ExpensePath;
import com.ftpix.sss.dsl.tables.MonthlyHistory.MonthlyHistoryPath;
import com.ftpix.sss.dsl.tables.RecurringExpense.RecurringExpensePath;
import com.ftpix.sss.dsl.tables.User.UserPath;
import com.ftpix.sss.dsl.tables.YearlyHistory.YearlyHistoryPath;
import com.ftpix.sss.dsl.tables.records.CategoryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Category extends TableImpl<CategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.category</code>
     */
    public static final Category CATEGORY = new Category();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoryRecord> getRecordType() {
        return CategoryRecord.class;
    }

    /**
     * The column <code>public.category.id</code>.
     */
    public final TableField<CategoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.category.icon</code>.
     */
    public final TableField<CategoryRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.category.category_order</code>.
     */
    public final TableField<CategoryRecord, Integer> CATEGORY_ORDER = createField(DSL.name("category_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.category.user_id</code>.
     */
    public final TableField<CategoryRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(48), this, "");

    private Category(Name alias, Table<CategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Category(Name alias, Table<CategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.category</code> table reference
     */
    public Category(String alias) {
        this(DSL.name(alias), CATEGORY);
    }

    /**
     * Create an aliased <code>public.category</code> table reference
     */
    public Category(Name alias) {
        this(alias, CATEGORY);
    }

    /**
     * Create a <code>public.category</code> table reference
     */
    public Category() {
        this(DSL.name("category"), null);
    }

    public <O extends Record> Category(Table<O> path, ForeignKey<O, CategoryRecord> childPath, InverseForeignKey<O, CategoryRecord> parentPath) {
        super(path, childPath, parentPath, CATEGORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CategoryPath extends Category implements Path<CategoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CategoryPath(Table<O> path, ForeignKey<O, CategoryRecord> childPath, InverseForeignKey<O, CategoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CategoryPath(Name alias, Table<CategoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CategoryPath as(String alias) {
            return new CategoryPath(DSL.name(alias), this);
        }

        @Override
        public CategoryPath as(Name alias) {
            return new CategoryPath(alias, this);
        }

        @Override
        public CategoryPath as(Table<?> alias) {
            return new CategoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PUBLIC.PUBLIC;
    }

    @Override
    public Identity<CategoryRecord, Long> getIdentity() {
        return (Identity<CategoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CategoryRecord> getPrimaryKey() {
        return Keys.CATEGORY_PKEY;
    }

    @Override
    public List<ForeignKey<CategoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CATEGORY__FK_CATEGORY_USER);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.CATEGORY__FK_CATEGORY_USER, null);

        return _user;
    }

    private transient ExpensePath _expense;

    /**
     * Get the implicit to-many join path to the <code>public.expense</code>
     * table
     */
    public ExpensePath expense() {
        if (_expense == null)
            _expense = new ExpensePath(this, null, Keys.EXPENSE__FK_EXPENSE_CATEGORY.getInverseKey());

        return _expense;
    }

    private transient MonthlyHistoryPath _monthlyHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>public.monthly_history</code> table
     */
    public MonthlyHistoryPath monthlyHistory() {
        if (_monthlyHistory == null)
            _monthlyHistory = new MonthlyHistoryPath(this, null, Keys.MONTHLY_HISTORY__FK_MONTHLY_HISTORY_CATEGORY.getInverseKey());

        return _monthlyHistory;
    }

    private transient RecurringExpensePath _recurringExpense;

    /**
     * Get the implicit to-many join path to the
     * <code>public.recurring_expense</code> table
     */
    public RecurringExpensePath recurringExpense() {
        if (_recurringExpense == null)
            _recurringExpense = new RecurringExpensePath(this, null, Keys.RECURRING_EXPENSE__FK_RECURRING_EXPENSE_CATEGORY.getInverseKey());

        return _recurringExpense;
    }

    private transient YearlyHistoryPath _yearlyHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>public.yearly_history</code> table
     */
    public YearlyHistoryPath yearlyHistory() {
        if (_yearlyHistory == null)
            _yearlyHistory = new YearlyHistoryPath(this, null, Keys.YEARLY_HISTORY__FK_YEARLY_HISTORY_CATEGORY.getInverseKey());

        return _yearlyHistory;
    }

    @Override
    public Category as(String alias) {
        return new Category(DSL.name(alias), this);
    }

    @Override
    public Category as(Name alias) {
        return new Category(alias, this);
    }

    @Override
    public Category as(Table<?> alias) {
        return new Category(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Category rename(String name) {
        return new Category(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Category rename(Name name) {
        return new Category(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Category rename(Table<?> name) {
        return new Category(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category where(Condition condition) {
        return new Category(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Category where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Category where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Category where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Category where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Category whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
