/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables;


import com.ftpix.sss.dsl.Keys;
import com.ftpix.sss.dsl.PUBLIC;
import com.ftpix.sss.dsl.tables.Expense.ExpensePath;
import com.ftpix.sss.dsl.tables.User.UserPath;
import com.ftpix.sss.dsl.tables.records.FilesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Files extends TableImpl<FilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.files</code>
     */
    public static final Files FILES = new Files();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FilesRecord> getRecordType() {
        return FilesRecord.class;
    }

    /**
     * The column <code>public.files.id</code>.
     */
    public final TableField<FilesRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(55).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.files.user_id</code>.
     */
    public final TableField<FilesRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(55).nullable(false), this, "");

    /**
     * The column <code>public.files.expense_id</code>.
     */
    public final TableField<FilesRecord, Long> EXPENSE_ID = createField(DSL.name("expense_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.files.status</code>.
     */
    public final TableField<FilesRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.files.ai_tags</code>.
     */
    public final TableField<FilesRecord, String> AI_TAGS = createField(DSL.name("ai_tags"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.files.amounts</code>.
     */
    public final TableField<FilesRecord, String> AMOUNTS = createField(DSL.name("amounts"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.files.file_name</code>.
     */
    public final TableField<FilesRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.files.time_created</code>.
     */
    public final TableField<FilesRecord, Long> TIME_CREATED = createField(DSL.name("time_created"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.files.time_updated</code>.
     */
    public final TableField<FilesRecord, Long> TIME_UPDATED = createField(DSL.name("time_updated"), SQLDataType.BIGINT.nullable(false), this, "");

    private Files(Name alias, Table<FilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Files(Name alias, Table<FilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.files</code> table reference
     */
    public Files(String alias) {
        this(DSL.name(alias), FILES);
    }

    /**
     * Create an aliased <code>public.files</code> table reference
     */
    public Files(Name alias) {
        this(alias, FILES);
    }

    /**
     * Create a <code>public.files</code> table reference
     */
    public Files() {
        this(DSL.name("files"), null);
    }

    public <O extends Record> Files(Table<O> path, ForeignKey<O, FilesRecord> childPath, InverseForeignKey<O, FilesRecord> parentPath) {
        super(path, childPath, parentPath, FILES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FilesPath extends Files implements Path<FilesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FilesPath(Table<O> path, ForeignKey<O, FilesRecord> childPath, InverseForeignKey<O, FilesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FilesPath(Name alias, Table<FilesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FilesPath as(String alias) {
            return new FilesPath(DSL.name(alias), this);
        }

        @Override
        public FilesPath as(Name alias) {
            return new FilesPath(alias, this);
        }

        @Override
        public FilesPath as(Table<?> alias) {
            return new FilesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PUBLIC.PUBLIC;
    }

    @Override
    public UniqueKey<FilesRecord> getPrimaryKey() {
        return Keys.FILES_PKEY;
    }

    @Override
    public List<ForeignKey<FilesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FILES__FK_SSS_FILE_EXPENSE, Keys.FILES__FK_SSS_FILE_USER);
    }

    private transient ExpensePath _expense;

    /**
     * Get the implicit join path to the <code>public.expense</code> table.
     */
    public ExpensePath expense() {
        if (_expense == null)
            _expense = new ExpensePath(this, Keys.FILES__FK_SSS_FILE_EXPENSE, null);

        return _expense;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FILES__FK_SSS_FILE_USER, null);

        return _user;
    }

    @Override
    public Files as(String alias) {
        return new Files(DSL.name(alias), this);
    }

    @Override
    public Files as(Name alias) {
        return new Files(alias, this);
    }

    @Override
    public Files as(Table<?> alias) {
        return new Files(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Files rename(String name) {
        return new Files(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Files rename(Name name) {
        return new Files(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Files rename(Table<?> name) {
        return new Files(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files where(Condition condition) {
        return new Files(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Files where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Files where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Files where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Files where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Files whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
