/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.ApiKeys;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApiKeysRecord extends UpdatableRecordImpl<ApiKeysRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.api_keys.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.api_keys.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.api_keys.keyname</code>.
     */
    public void setKeyname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.api_keys.keyname</code>.
     */
    public String getKeyname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.api_keys.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.api_keys.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.api_keys.timecreated</code>.
     */
    public void setTimecreated(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.api_keys.timecreated</code>.
     */
    public Long getTimecreated() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.api_keys.lastused</code>.
     */
    public void setLastused(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.api_keys.lastused</code>.
     */
    public Long getLastused() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.api_keys.expirydate</code>.
     */
    public void setExpirydate(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.api_keys.expirydate</code>.
     */
    public Long getExpirydate() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.api_keys.apikey</code>.
     */
    public void setApikey(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.api_keys.apikey</code>.
     */
    public String getApikey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.api_keys.apikeyhash</code>.
     */
    public void setApikeyhash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.api_keys.apikeyhash</code>.
     */
    public String getApikeyhash() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiKeysRecord
     */
    public ApiKeysRecord() {
        super(ApiKeys.API_KEYS);
    }

    /**
     * Create a detached, initialised ApiKeysRecord
     */
    public ApiKeysRecord(String id, String keyname, String userId, Long timecreated, Long lastused, Long expirydate, String apikey, String apikeyhash) {
        super(ApiKeys.API_KEYS);

        setId(id);
        setKeyname(keyname);
        setUserId(userId);
        setTimecreated(timecreated);
        setLastused(lastused);
        setExpirydate(expirydate);
        setApikey(apikey);
        setApikeyhash(apikeyhash);
        resetChangedOnNotNull();
    }
}
