/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.Category;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.category.icon</code>.
     */
    public void setIcon(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.category.icon</code>.
     */
    public String getIcon() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.category.category_order</code>.
     */
    public void setCategoryOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.category.category_order</code>.
     */
    public Integer getCategoryOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.category.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.category.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(Long id, String icon, Integer categoryOrder, String userId) {
        super(Category.CATEGORY);

        setId(id);
        setIcon(icon);
        setCategoryOrder(categoryOrder);
        setUserId(userId);
        resetTouchedOnNotNull();
    }
}
