/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.Expense;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExpenseRecord extends UpdatableRecordImpl<ExpenseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.expense.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.expense.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.expense.amount</code>.
     */
    public void setAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.expense.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.expense.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.expense.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.expense.date</code>.
     */
    public void setDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.expense.date</code>.
     */
    public String getDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.expense.type</code>.
     */
    public void setType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.expense.type</code>.
     */
    public Integer getType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.expense.income</code>.
     */
    public void setIncome(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.expense.income</code>.
     */
    public Integer getIncome() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.expense.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.expense.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.expense.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.expense.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.expense.note</code>.
     */
    public void setNote(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.expense.note</code>.
     */
    public String getNote() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.expense.time</code>.
     */
    public void setTime(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.expense.time</code>.
     */
    public String getTime() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.expense.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.expense.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.expense.timecreated</code>.
     */
    public void setTimecreated(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.expense.timecreated</code>.
     */
    public Long getTimecreated() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExpenseRecord
     */
    public ExpenseRecord() {
        super(Expense.EXPENSE);
    }

    /**
     * Create a detached, initialised ExpenseRecord
     */
    public ExpenseRecord(Long id, Double amount, Long categoryId, String date, Integer type, Integer income, Double latitude, Double longitude, String note, String time, Long timestamp, Long timecreated) {
        super(Expense.EXPENSE);

        setId(id);
        setAmount(amount);
        setCategoryId(categoryId);
        setDate(date);
        setType(type);
        setIncome(income);
        setLatitude(latitude);
        setLongitude(longitude);
        setNote(note);
        setTime(time);
        setTimestamp(timestamp);
        setTimecreated(timecreated);
        resetTouchedOnNotNull();
    }
}
