/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.Files;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilesRecord extends UpdatableRecordImpl<FilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.files.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.files.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.files.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.files.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.files.expense_id</code>.
     */
    public void setExpenseId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.files.expense_id</code>.
     */
    public Long getExpenseId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.files.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.files.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.files.ai_tags</code>.
     */
    public void setAiTags(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.files.ai_tags</code>.
     */
    public String getAiTags() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.files.amounts</code>.
     */
    public void setAmounts(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.files.amounts</code>.
     */
    public String getAmounts() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.files.file_name</code>.
     */
    public void setFileName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.files.file_name</code>.
     */
    public String getFileName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.files.time_created</code>.
     */
    public void setTimeCreated(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.files.time_created</code>.
     */
    public Long getTimeCreated() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.files.time_updated</code>.
     */
    public void setTimeUpdated(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.files.time_updated</code>.
     */
    public Long getTimeUpdated() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilesRecord
     */
    public FilesRecord() {
        super(Files.FILES);
    }

    /**
     * Create a detached, initialised FilesRecord
     */
    public FilesRecord(String id, String userId, Long expenseId, String status, String aiTags, String amounts, String fileName, Long timeCreated, Long timeUpdated) {
        super(Files.FILES);

        setId(id);
        setUserId(userId);
        setExpenseId(expenseId);
        setStatus(status);
        setAiTags(aiTags);
        setAmounts(amounts);
        setFileName(fileName);
        setTimeCreated(timeCreated);
        setTimeUpdated(timeUpdated);
        resetTouchedOnNotNull();
    }
}
