/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.Household;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HouseholdRecord extends UpdatableRecordImpl<HouseholdRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.household.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.household.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HouseholdRecord
     */
    public HouseholdRecord() {
        super(Household.HOUSEHOLD);
    }

    /**
     * Create a detached, initialised HouseholdRecord
     */
    public HouseholdRecord(String id) {
        super(Household.HOUSEHOLD);

        setId(id);
        resetChangedOnNotNull();
    }
}
