/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.HouseholdMembers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HouseholdMembersRecord extends UpdatableRecordImpl<HouseholdMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.household_members.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.household_members.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.household_members.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.household_members.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.household_members.invited_by_id</code>.
     */
    public void setInvitedById(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.household_members.invited_by_id</code>.
     */
    public String getInvitedById() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.household_members.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.household_members.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.household_members.admin</code>.
     */
    public void setAdmin(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.household_members.admin</code>.
     */
    public Boolean getAdmin() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.household_members.color</code>.
     */
    public void setColor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.household_members.color</code>.
     */
    public String getColor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.household_members.household_id</code>.
     */
    public void setHouseholdId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.household_members.household_id</code>.
     */
    public String getHouseholdId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HouseholdMembersRecord
     */
    public HouseholdMembersRecord() {
        super(HouseholdMembers.HOUSEHOLD_MEMBERS);
    }

    /**
     * Create a detached, initialised HouseholdMembersRecord
     */
    public HouseholdMembersRecord(String id, String userId, String invitedById, String status, Boolean admin, String color, String householdId) {
        super(HouseholdMembers.HOUSEHOLD_MEMBERS);

        setId(id);
        setUserId(userId);
        setInvitedById(invitedById);
        setStatus(status);
        setAdmin(admin);
        setColor(color);
        setHouseholdId(householdId);
        resetTouchedOnNotNull();
    }
}
