/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.MonthlyHistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonthlyHistoryRecord extends UpdatableRecordImpl<MonthlyHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.monthly_history.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.monthly_history.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.monthly_history.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.monthly_history.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.monthly_history.total</code>.
     */
    public void setTotal(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.monthly_history.total</code>.
     */
    public Double getTotal() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.monthly_history.date</code>.
     */
    public void setDate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.monthly_history.date</code>.
     */
    public Integer getDate() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonthlyHistoryRecord
     */
    public MonthlyHistoryRecord() {
        super(MonthlyHistory.MONTHLY_HISTORY);
    }

    /**
     * Create a detached, initialised MonthlyHistoryRecord
     */
    public MonthlyHistoryRecord(String id, Long categoryId, Double total, Integer date) {
        super(MonthlyHistory.MONTHLY_HISTORY);

        setId(id);
        setCategoryId(categoryId);
        setTotal(total);
        setDate(date);
        resetTouchedOnNotNull();
    }
}
