/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.ResetPassword;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResetPasswordRecord extends UpdatableRecordImpl<ResetPasswordRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reset_password.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reset_password.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.reset_password.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reset_password.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.reset_password.expirydate</code>.
     */
    public void setExpirydate(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reset_password.expirydate</code>.
     */
    public Long getExpirydate() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResetPasswordRecord
     */
    public ResetPasswordRecord() {
        super(ResetPassword.RESET_PASSWORD);
    }

    /**
     * Create a detached, initialised ResetPasswordRecord
     */
    public ResetPasswordRecord(String id, String userId, Long expirydate) {
        super(ResetPassword.RESET_PASSWORD);

        setId(id);
        setUserId(userId);
        setExpirydate(expirydate);
        resetChangedOnNotNull();
    }
}
