/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.User;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.lastname</code>.
     */
    public void setLastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.lastname</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.subscriptionexpirydate</code>.
     */
    public void setSubscriptionexpirydate(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user.subscriptionexpirydate</code>.
     */
    public Long getSubscriptionexpirydate() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.user.showannouncement</code>.
     */
    public void setShowannouncement(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user.showannouncement</code>.
     */
    public Integer getShowannouncement() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.user.isadmin</code>.
     */
    public void setIsadmin(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user.isadmin</code>.
     */
    public Integer getIsadmin() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.user.oidcsub</code>.
     */
    public void setOidcsub(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user.oidcsub</code>.
     */
    public String getOidcsub() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.user.password_bcrypt</code>.
     */
    public void setPasswordBcrypt(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user.password_bcrypt</code>.
     */
    public String getPasswordBcrypt() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String id, String email, String firstname, String password, String lastname, Long subscriptionexpirydate, Integer showannouncement, Integer isadmin, String oidcsub, String passwordBcrypt) {
        super(User.USER);

        setId(id);
        setEmail(email);
        setFirstname(firstname);
        setPassword(password);
        setLastname(lastname);
        setSubscriptionexpirydate(subscriptionexpirydate);
        setShowannouncement(showannouncement);
        setIsadmin(isadmin);
        setOidcsub(oidcsub);
        setPasswordBcrypt(passwordBcrypt);
        resetChangedOnNotNull();
    }
}
