/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.User;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record8<String, String, String, String, String, Long, Byte, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sss.USER.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sss.USER.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sss.USER.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sss.USER.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sss.USER.FIRSTNAME</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sss.USER.FIRSTNAME</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sss.USER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sss.USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sss.USER.LASTNAME</code>.
     */
    public void setLastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sss.USER.LASTNAME</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sss.USER.SUBSCRIPTIONEXPIRYDATE</code>.
     */
    public void setSubscriptionexpirydate(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>sss.USER.SUBSCRIPTIONEXPIRYDATE</code>.
     */
    public Long getSubscriptionexpirydate() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>sss.USER.SHOWANNOUNCEMENT</code>.
     */
    public void setShowannouncement(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>sss.USER.SHOWANNOUNCEMENT</code>.
     */
    public Byte getShowannouncement() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>sss.USER.ISADMIN</code>.
     */
    public void setIsadmin(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>sss.USER.ISADMIN</code>.
     */
    public Byte getIsadmin() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, String, String, Long, Byte, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, String, String, String, Long, Byte, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return User.USER.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return User.USER.LASTNAME;
    }

    @Override
    public Field<Long> field6() {
        return User.USER.SUBSCRIPTIONEXPIRYDATE;
    }

    @Override
    public Field<Byte> field7() {
        return User.USER.SHOWANNOUNCEMENT;
    }

    @Override
    public Field<Byte> field8() {
        return User.USER.ISADMIN;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getLastname();
    }

    @Override
    public Long component6() {
        return getSubscriptionexpirydate();
    }

    @Override
    public Byte component7() {
        return getShowannouncement();
    }

    @Override
    public Byte component8() {
        return getIsadmin();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getLastname();
    }

    @Override
    public Long value6() {
        return getSubscriptionexpirydate();
    }

    @Override
    public Byte value7() {
        return getShowannouncement();
    }

    @Override
    public Byte value8() {
        return getIsadmin();
    }

    @Override
    public UserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public UserRecord value6(Long value) {
        setSubscriptionexpirydate(value);
        return this;
    }

    @Override
    public UserRecord value7(Byte value) {
        setShowannouncement(value);
        return this;
    }

    @Override
    public UserRecord value8(Byte value) {
        setIsadmin(value);
        return this;
    }

    @Override
    public UserRecord values(String value1, String value2, String value3, String value4, String value5, Long value6, Byte value7, Byte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String id, String email, String firstname, String password, String lastname, Long subscriptionexpirydate, Byte showannouncement, Byte isadmin) {
        super(User.USER);

        setId(id);
        setEmail(email);
        setFirstname(firstname);
        setPassword(password);
        setLastname(lastname);
        setSubscriptionexpirydate(subscriptionexpirydate);
        setShowannouncement(showannouncement);
        setIsadmin(isadmin);
    }
}
