/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl.tables.records;


import com.ftpix.sss.dsl.tables.YearlyHistory;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class YearlyHistoryRecord extends TableRecordImpl<YearlyHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.yearly_history.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.yearly_history.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.yearly_history.date</code>.
     */
    public void setDate(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.yearly_history.date</code>.
     */
    public Integer getDate() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.yearly_history.total</code>.
     */
    public void setTotal(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.yearly_history.total</code>.
     */
    public Double getTotal() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.yearly_history.expenses</code>.
     */
    public void setExpenses(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.yearly_history.expenses</code>.
     */
    public Long getExpenses() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YearlyHistoryRecord
     */
    public YearlyHistoryRecord() {
        super(YearlyHistory.YEARLY_HISTORY);
    }

    /**
     * Create a detached, initialised YearlyHistoryRecord
     */
    public YearlyHistoryRecord(Long categoryId, Integer date, Double total, Long expenses) {
        super(YearlyHistory.YEARLY_HISTORY);

        setCategoryId(categoryId);
        setDate(date);
        setTotal(total);
        setExpenses(expenses);
        resetChangedOnNotNull();
    }
}
