import React from 'react';
import Amount from "../Amount.jsx";

export default class RecurringExpense extends React.Component {

    constructor(props) {
        super(props);
        this.state = {flip: false, confirm: false, menu: false}

        this.getFrequence = this.getFrequence.bind(this);
        this.flip = this.flip.bind(this);
        this.toggleConfirm = this.toggleConfirm.bind(this);
        this.toggleMenu = this.toggleMenu.bind(this);
    }

    /**
     * Flips the card
     */
    flip() {
        this.setState({flip: !this.state.flip});
    }

    /**
     * Toggles the delete menu
     */
    toggleMenu(e) {
        e.stopPropagation();
        this.setState({menu: !this.state.menu, confirm: false});
    }

    /**
     * Get the recurring expense frequence
     * @param type
     * @returns {*}
     */
    getFrequence(type) {
        switch (type) {
            case 0:
                return 'Daily'
            case 1:
                return 'Weekly';
            case 2:
                return 'Monthly';
            case 3:
                return 'Yearly';
        }
    }

    toggleConfirm(e) {
        // e.stopPropagation();
        this.setState({confirm: !this.state.confirm});
    }

    render() {
        return <div className={'RecurringExpense'} onClick={this.flip}>
            <div className={'bar '+(this.state.flip === true ?'flip':'')} style={this.props.style}>
                {this.state.flip === false &&
                <div className={'front fade-in '}>
                    <div className={'frequence'}>
                        {this.getFrequence(this.props.expense.type)}
                    </div>
                    <div className={'icon'}>
                        <i className={'cat ' + this.props.expense.category.icon}></i>
                    </div>
                    <div className={'amount'}>
                        <Amount>{this.props.expense.amount}</Amount>
                    </div>
                </div>
                }
                {this.state.flip === true &&
                <div className={"back fade-in"}>
                    <i className={'fa fa-ellipsis-v'} onClick={this.toggleMenu}/>
                    <p>Last occurrence: <span className="date">{this.props.expense.lastOccurrence}</span></p>
                    <p>Next occurrence: <span className='date'>{this.props.expense.nextOccurrence}</span></p>

                    <div className={'bottom-menu ' + (this.state.menu ? 'showing' : '')}
                         onClick={(e) => e.stopPropagation()}>
                        <i className={'fa fa-times'} onClick={this.toggleMenu}/>
                        {!this.state.confirm &&
                        <p onClick={this.toggleConfirm} className={'delete'}>Delete</p>
                        }
                        {this.state.confirm &&
                        <div>
                            <p>
                                Are you sure ?&nbsp;
                                <small>This won't delete the previous expenses generated by this recurring expense.
                                </small>
                            </p>
                            <p className={'options'}>
                                <span onClick={() => this.setState({confirm: false})}>Cancel</span>
                                <span className={'ok'}
                                      onClick={() => this.props.delete(this.props.expense.id)}>Ok</span>
                            </p>
                        </div>
                        }
                    </div>
                </div>
                }
            </div>
        </div>
    }
}