# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
       key_id: "VNWUR4CJX5",
       issuer_id: "7ec03c17-e05f-400d-a3d3-35b57a6c6f67",
       key_filepath: "/Users/gz/AuthKey_VNWUR4CJX5.p8",
       duration: 1200, # optional (maximum 1200)
       in_house: false # optional but may be required if using match/sigh
     )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(build_number: ENV['DRONE_TAG'])
    upload_to_app_store(
        build_number: ENV['DRONE_TAG'],
        submit_for_review: true,
        automatic_release: true,
        skip_binary_upload: true,
        submission_information: {
            add_id_info_uses_idfa: false,
            export_compliance_platform: 'ios',
            export_compliance_uses_encryption: true,
            export_compliance_is_exempt: true,

            # These are the ones I am confused by
            export_compliance_compliance_required: false,
            export_compliance_encryption_updated: false,
            export_compliance_app_type: nil,
            export_compliance_contains_third_party_cryptography: false,
            export_compliance_contains_proprietary_cryptography: false,
            export_compliance_available_on_french_store: false
        }
    )
  end
end
