/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl;


import com.ftpix.sss.dsl.tables.MonthlyHistory;
import com.ftpix.sss.dsl.tables.YearlyHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in sss.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MONTHLY_HISTORY_MONTHLY_HISTORY_DATE_IDX = Internal.createIndex(DSL.name("monthly_history_date_idx"), MonthlyHistory.MONTHLY_HISTORY, new OrderField[] { MonthlyHistory.MONTHLY_HISTORY.DATE }, false);
    public static final Index YEARLY_HISTORY_YEARLY_HISTORY_DATE_IDX = Internal.createIndex(DSL.name("yearly_history_date_idx"), YearlyHistory.YEARLY_HISTORY, new OrderField[] { YearlyHistory.YEARLY_HISTORY.DATE }, false);
}
