/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl;


import com.ftpix.sss.dsl.tables.FlywaySchemaHistory;
import com.ftpix.sss.dsl.tables.MonthlyHistory;
import com.ftpix.sss.dsl.tables.YearlyHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index MONTHLY_HISTORY_DATE_IDX = Internal.createIndex(DSL.name("monthly_history_date_idx"), MonthlyHistory.MONTHLY_HISTORY, new OrderField[] { MonthlyHistory.MONTHLY_HISTORY.DATE }, false);
    public static final Index MONTHLY_HISTORY_UNIQUE_IDX = Internal.createIndex(DSL.name("monthly_history_unique_idx"), MonthlyHistory.MONTHLY_HISTORY, new OrderField[] { MonthlyHistory.MONTHLY_HISTORY.CATEGORY_ID, MonthlyHistory.MONTHLY_HISTORY.DATE }, true);
    public static final Index YEARLY_HISTORY_DATE_IDX = Internal.createIndex(DSL.name("yearly_history_date_idx"), YearlyHistory.YEARLY_HISTORY, new OrderField[] { YearlyHistory.YEARLY_HISTORY.DATE }, false);
    public static final Index YEARLY_HISTORY_UNIQUE = Internal.createIndex(DSL.name("yearly_history_unique"), YearlyHistory.YEARLY_HISTORY, new OrderField[] { YearlyHistory.YEARLY_HISTORY.CATEGORY_ID, YearlyHistory.YEARLY_HISTORY.DATE }, true);
}
