/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl;


import com.ftpix.sss.dsl.tables.ApiKeys;
import com.ftpix.sss.dsl.tables.Expense;
import com.ftpix.sss.dsl.tables.FlywaySchemaHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index API_KEYS_HASH = Internal.createIndex(DSL.name("api_keys_hash"), ApiKeys.API_KEYS, new OrderField[] { ApiKeys.API_KEYS.APIKEYHASH }, false);
    public static final Index EXPENSE_CATEGORY_TIME = Internal.createIndex(DSL.name("expense_category_time"), Expense.EXPENSE, new OrderField[] { Expense.EXPENSE.CATEGORY_ID, Expense.EXPENSE.TIMESTAMP }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index UNIQUE_API_KEY = Internal.createIndex(DSL.name("unique_api_key"), ApiKeys.API_KEYS, new OrderField[] { ApiKeys.API_KEYS.APIKEY }, true);
}
