/*
 * This file is generated by jOOQ.
 */
package com.ftpix.sss.dsl;


import com.ftpix.sss.dsl.tables.Category;
import com.ftpix.sss.dsl.tables.Expense;
import com.ftpix.sss.dsl.tables.MonthlyHistory;
import com.ftpix.sss.dsl.tables.RecurringExpense;
import com.ftpix.sss.dsl.tables.ResetPassword;
import com.ftpix.sss.dsl.tables.SchemaVersion;
import com.ftpix.sss.dsl.tables.Settings;
import com.ftpix.sss.dsl.tables.User;
import com.ftpix.sss.dsl.tables.YearlyHistory;


/**
 * Convenience access to all tables in sss.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sss.CATEGORY</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>sss.EXPENSE</code>.
     */
    public static final Expense EXPENSE = Expense.EXPENSE;

    /**
     * The table <code>sss.MONTHLY_HISTORY</code>.
     */
    public static final MonthlyHistory MONTHLY_HISTORY = MonthlyHistory.MONTHLY_HISTORY;

    /**
     * The table <code>sss.RECURRING_EXPENSE</code>.
     */
    public static final RecurringExpense RECURRING_EXPENSE = RecurringExpense.RECURRING_EXPENSE;

    /**
     * The table <code>sss.RESET_PASSWORD</code>.
     */
    public static final ResetPassword RESET_PASSWORD = ResetPassword.RESET_PASSWORD;

    /**
     * The table <code>sss.SCHEMA_VERSION</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>sss.SETTINGS</code>.
     */
    public static final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>sss.USER</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>sss.YEARLY_HISTORY</code>.
     */
    public static final YearlyHistory YEARLY_HISTORY = YearlyHistory.YEARLY_HISTORY;
}
